### PR TITLE
Format notifications for merge process

### LINKED ISSUE #3854: Properly format notifications from merge process
Screenshot 2023-07-27 at 1 13 07 PM

Types that need to be handled:
- `record-merge-starting`
- `record-merge-pending`
- `record-merge-succeeded`
- `record-merge-failed`

See the `record_merge` file for more information.

The succeeded notification should have a link to the newly merged record, with the URL constructed based on the table name and record ID.

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #3854

### CODE REVIEW

**Review by grantfitzsimmons — APPROVED** [review]
I cannot find a way to create a notification with `record-merge-pending` anymore. I don't see it referenced in the code. Since this is potentially not a problem, I will approve. Not sure if it was removed during the dev process.

File: specifyweb/frontend/js_src/lib/components/Header/NotificationRenderers.tsx [hunk 1]
```diff
@@ -119,6 +123,30 @@ export const notificationRenderers: IR<
       />
     );
   },
+  'record-merge-starting'() {
+    return mergingText.mergingHasStarted();
+  },
+  'record-merge-failed'() {
+    return mergingText.mergingFailed();
+  },
```
Comment (melton-jason) [inline specifyweb/frontend/js_src/lib/components/Header/NotificationRenderers.tsx:131]: (optional) Preferably, we would include more information for these two processes. Namely, an identifier that the user can use to keep track of which merging process is which. This can be something like the table and id of the merged record, or the celery task id itself. 

There can be multiple merges ongoing at the same time, and when the user just receives "Your merging process failed", it can be impossible to differentiate _which_ one failed.

Comment (melton-jason) [reply specifyweb/frontend/js_src/lib/components/Header/NotificationRenderers.tsx:131]: (optional) 
On the topic of providing more information, I would love to have a link to the Merge Records dialog from the `record-merge-failed` notification. 
You should be able to construct the URL using the ids of the records (which is included in the payload). 
(The url is in the format `http://localhost/specify/overlay/merge/Agent/?records=9,10,11`, where records is an "array" of the ids)

See https://github.com/specify/specify7/blob/3b6a6ab6593bbb790a05a90d58bf35d2b484e51a/specifyweb/frontend/js_src/lib/components/Merging/index.tsx#L88-L90C12

Also, including the reason might be beneficial for debugging purposes. At the very least, I would hide the reason under a "dropdown" (details). 
If that is still too far, we should have the reason when the frontend is in DEBUG mode

File: specifyweb/frontend/js_src/lib/components/Header/NotificationRenderers.tsx [hunk 2]
```diff
@@ -119,6 +123,30 @@ export const notificationRenderers: IR<
...
+    const model = getModel(tableName);
+    const resource =
+      typeof model === 'object' ? new model.Resource({ id }) : undefined;
+    return (
+      resource !== undefined && (
+        <>
+          {mergingText.mergingSucceeded()}
+          <Link.NewTab href={`/specify/view/${tableName}/${id}`}>
+            <TableIcon label name={tableName} />
+            <FormattedResource asLink={false} resource={resource} />
```
Comment (melton-jason) [inline specifyweb/frontend/js_src/lib/components/Header/NotificationRenderers.tsx:144]: `FormattedResource` as a link already opens the resource in a new tab. Why did you need to wrap it in a `Link.NewTab` and set the `FormattedResource` to not be a link. 
Was it it be consistent with other Notification links?

**Review by melton-jason — CHANGES_REQUESTED** [review]

**Comment by CarolineDenis** [comment]
> I cannot find a way to create a notification with `record-merge-pending` anymore. I don't see it referenced in the code. Since this is potentially not a problem, I will approve. Not sure if it was removed during the dev process.

@acwhite211 confirmed me this wasn't used

File: specifyweb/frontend/js_src/lib/components/Header/NotificationRenderers.tsx (hunk 2 above)
Comment (CarolineDenis) [reply specifyweb/frontend/js_src/lib/components/Header/NotificationRenderers.tsx:144]: No you are right. I didn't have FormattedResource at first and didn't remove it once I implemented it

File: specifyweb/frontend/js_src/lib/components/Header/NotificationRenderers.tsx [hunk 3]
```diff
@@ -119,6 +124,67 @@ export const notificationRenderers: IR<
...
+    const tableName = notification.payload.table;
+    const collectionId = parseInt(notification.payload.collection_id);
+    const mergeName = notification.payload.name;
+    const schemaResource = new schema.models.Collection.Resource({
+      id: collectionId,
+    });
+    const [collectionName, setCollectionName] = React.useState<string | null>(
+      ''
+    );
+    schemaResource
```
Comment (maxxxxxdlp) [inline specifyweb/frontend/js_src/lib/components/Header/NotificationRenderers.tsx:137]: did you forget to wrap this in a useEffect?

you are creating a new collection resource on each render, and then making a network request on each render, and that network request modifies the state. That's a recipe for a terrible performance or an infinite loop!

fetching data outside of useEffect is not allowed (though, recently added react server components would allow for this, but only on the back-end)
you don't know how many times the render function will get called

ideally, the render method should not have any side effects at all

File: specifyweb/frontend/js_src/lib/components/Header/NotificationRenderers.tsx [hunk 4]
```diff
@@ -119,6 +124,67 @@ export const notificationRenderers: IR<
...
+    const tableName = notification.payload.table;
+    const id = parseInt(notification.payload.new_record_id);
+    const ids = [JSON.parse(notification.payload.old_record_ids), id];
+    return (
+      <>
+        {mergingText.mergingHasFailed()}
+        <div className="flex items-center gap-2">
+          <TableIcon label name={tableName} />
+          <Link.NewTab
+            href={`/specify/overlay/merge/${tableName}/?${mergingQueryParameter}=${ids}`}
```
Comment (maxxxxxdlp) [inline specifyweb/frontend/js_src/lib/components/Header/NotificationRenderers.tsx:162]: don't do this by hand. call `formatUrl` instead

File: specifyweb/frontend/js_src/lib/components/Header/NotificationRenderers.tsx [hunk 5]
```diff
@@ -119,6 +124,67 @@ export const notificationRenderers: IR<
...
+          </Link.NewTab>
+        </div>
+      </>
+    );
+  },
+  'record-merge-succeeded'(notification) {
+    const id = parseInt(notification.payload.new_record_id);
+    const tableName = notification.payload.table;
+    const model = getModel(tableName);
+    const resource =
```
Comment (maxxxxxdlp) [inline specifyweb/frontend/js_src/lib/components/Header/NotificationRenderers.tsx:174]: do not create a new resource on each render! you muse call useMemo

`FormattedResource` makes a network request to fetch and format the resource every time the resource changes - which it does on every render here

**Review by maxxxxxdlp — CHANGES_REQUESTED** [review]
Bad. Some basic React rules violated

**Comment by grantfitzsimmons** [comment]
@melton-jason Can you review this PR sooner?

**Review by melton-jason — CHANGES_REQUESTED** [review]

File: specifyweb/frontend/js_src/lib/components/Header/NotificationRenderers.tsx [hunk 6]
```diff
@@ -128,15 +130,17 @@ export const notificationRenderers: IR<
...
-      .fetch()
-      .then((resource) => setCollectionName(resource.get('collectionName')));
+    const [collectionName, setCollectionName] = React.useState<
+      string | null | undefined
+    >('');
+
+    React.useEffect(() => {
+      setCollectionName(collection?.collectionName);
+    }, [collection]);
+
```
Comment (maxxxxxdlp) [inline specifyweb/frontend/js_src/lib/components/Header/NotificationRenderers.tsx:143]: why so complex?

```suggestion
const collectionName = collection?.collectionName;
```

and then you don't even need to create a variable and can use `collection?.collectionName` directly in the `return ...`

File: specifyweb/frontend/js_src/lib/components/Header/NotificationRenderers.tsx [hunk 7]
```diff
@@ -119,6 +126,74 @@ export const notificationRenderers: IR<
...
+    return (
+      <>
+        {mergingText.mergingHasStarted()}
+        <div className="flex items-center gap-2">
+          <TableIcon label name={tableName} />
+          <p>
+            {collectionName} {'-'} {mergeName}
```
Comment (maxxxxxdlp) [inline specifyweb/frontend/js_src/lib/components/Header/NotificationRenderers.tsx:150]: Relying on JSX for spaces is very unsafe as Prettier does not try to preserve spaces when reformatting JSX, thus this can break in the future.

```suggestion
            {`${collectionName} - ${mergeName}`}
```

File: specifyweb/frontend/js_src/lib/components/Header/NotificationRenderers.tsx [hunk 8]
```diff
@@ -119,6 +126,74 @@ export const notificationRenderers: IR<
...
+    const tableName = notification.payload.table;
+    const id = parseInt(notification.payload.new_record_id);
+    const ids = [JSON.parse(notification.payload.old_record_ids), id];
+    return (
+      <>
+        {mergingText.mergingHasFailed()}
+        <div className="flex items-center gap-2">
+          <TableIcon label name={tableName} />
+          <Link.NewTab
+            href={formatUrl(`/specify/overlay/merge/${tableName}/`, {
```
Comment (maxxxxxdlp) [inline specifyweb/frontend/js_src/lib/components/Header/NotificationRenderers.tsx:166]: (optional) this is a bit too complex. for readability, can you extract it into a variable, and just use that variable here?

that will make code more readable

**Review by maxxxxxdlp — CHANGES_REQUESTED** [review]

**Review by melton-jason — APPROVED** [review]
