### PR TITLE
Disable tree actions in view mode

### LINKED ISSUE #5007: Tree actions remain accessible in read-only mode
**Describe the bug**
In read-only mode, users with tree permissions can still access the tree actions they have roles for (e.g. move, merge, synonymize).

**To Reproduce**

1. Login to or create a user that has tree permissions
2. Go to a tree
3. Enable read-only mode
4. See that you can still access tree actions

**Expected behavior**
You should only be able to search or view tree nodes in read-only mode.

**Screenshots**

https://github.com/specify/specify7/assets/130881183/0dda02ef-1624-4810-8baf-21abd722213e

What it should be:

Please, also fill out the following information manually:

- OS: macOS 14.5
- Browser: Chrome
- Specify 7 Version: Tested in edge & PR #5001
- Database Name: KUFish_5_16_23
- Collection name: KU Fish Voucher Collection
- User Name: spfishadmin & testread

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #5007

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good and
      self-explanatory (or properly documented)
- [ ] Add relevant issue to release milestone

### Testing instructions

- Login to or create a user that has tree permissions
- Go to a tree
- Enable read-only mode
- [ ] Verify tree actions are disabled

### CODE REVIEW

File: specifyweb/frontend/js_src/lib/components/TreeView/Actions.tsx [hunk 1]
```diff
@@ -117,7 +119,7 @@ export function TreeViewActions<SCHEMA extends AnyTree>({
           disabled={focusedRow === undefined}
           isRoot={isRoot}
           label={
-            hasTablePermission(tableName, 'update')
+            isViewMode
               ? commonText.edit()
               : commonText.view()
```
Comment (sharadsw) [inline specifyweb/frontend/js_src/lib/components/TreeView/Actions.tsx:124]: Currently, the button says Edit instead of View when read only mode is turned on

File: specifyweb/frontend/js_src/lib/components/TreeView/Actions.tsx [hunk 2]
```diff
@@ -76,6 +76,8 @@ export function TreeViewActions<SCHEMA extends AnyTree>({
   const disableButtons =
     focusedRow === undefined || typeof currentAction === 'string';
 
+  const isViewMode = !hasTablePermission(tableName, 'update');
+
```
Comment (sharadsw) [inline specifyweb/frontend/js_src/lib/components/TreeView/Actions.tsx:80]: Just to make things consistent with other parts of Specify, I wonder if we could use `ReadonlyContext` here?
We can do something like
```
const isReadOnly = React.useContext(ReadOnlyContext);
```
and then use `isReadOnly` instead of `isViewMode`.

Functionally nothing will change but it will just ensure we handle readonly mode in the same way everywhere.

**Review by emenslin — APPROVED** [review]

**Review by sharadsw — APPROVED** [review]

**Review by acwhite211 — APPROVED** [review]

**Review by grantfitzsimmons — APPROVED** [review]
- [X] Verify tree actions are disabled

image
