### PR TITLE
Disable change label field when unsaved changes in app resource

### LINKED ISSUE #4421: `xml-editor`: 'Show Data Model Field Names' does not prompt the user to save before reloading
**Describe the bug**
When pressed, the 'Show Data Model Field Names' button refreshes the page and the user loses their progress.

**To Reproduce**
1. Go to a form definition
2. Add a new view definition for a table
3. Make some edits
4. Click on the 'Show Data Model Field Names' button
5. See that you reload the page while the changes aren't preserved
6. See that you now see a 404

**Expected behavior**
If the button is going to reload the page, it should first ask the user to save so that they do not lose the changes they've been working on.

**Screenshots**

https://github.com/specify/specify7/assets/37256050/9eaa7f63-d2c0-44bf-9d55-fcb45e6ee6d9

**Desktop:**
macOS, Arc, `xml-editor`

https://crazyfish-xml-editor.test.specifysystems.org/specify/resources/view-set/4/CollectionObject/CollectionObject

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #4421

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [x] Add relevant issue to release milestone

### Testing instructions
	•	open app resource
	•	open a view definition
	•	click on "Show Localized/Data Model Field Labels" button
	•	verify it works
	•	make a change in the view def
	•	verify that the button to change the field label is disabled

### CODE REVIEW

File: specifyweb/frontend/js_src/lib/components/FormEditor/Editor.tsx [hunk 1]
```diff
@@ -73,6 +74,8 @@ export function FormEditor(): JSX.Element {
       ? userText.switchToHorizontalLayout()
       : userText.switchToVerticalLayout();
 
+  const unloadProtects = React.useContext(UnloadProtectsContext)!;
```
Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/components/FormEditor/Editor.tsx:77]: why not just move this line into the UseLabelsSchema component, rather than do prop drilling?

**Review by maxpatiiuk — CHANGES_REQUESTED** [review]

File: specifyweb/frontend/js_src/lib/components/FormEditor/Editor.tsx (hunk 1 above)
Comment (CarolineDenis) [reply specifyweb/frontend/js_src/lib/components/FormEditor/Editor.tsx]: good question... I should have had

**Review by maxpatiiuk — APPROVED** [review]

File: specifyweb/frontend/js_src/lib/components/FormEditor/Editor.tsx [hunk 2]
```diff
@@ -195,8 +196,10 @@ function UseLabelsSchema(): JSX.Element {
     globalThis.location.reload();
```
Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/components/FormEditor/Editor.tsx:196]: can you confirm that this the unload protect was correctly set, but wasn't being triggered by this `reload()` command?

i.e if you make changes and then try to use the back/forward browser buttons, do you get the unload protect dialog?

Comment (CarolineDenis) [reply specifyweb/frontend/js_src/lib/components/FormEditor/Editor.tsx:196]: no you don't

**Review by emenslin — APPROVED** [review]
Looks good, button is disabled when you haven't saved. 
Screenshot 2024-01-25 111627

**Review by grantfitzsimmons — APPROVED** [review]
