### PR TITLE
Keep new unique name when cloning resource

### LINKED ISSUE #4517: Cloned app resources do not receive an auto-incremented number in the title
**Describe the bug**
Cloned records are supposed to have a (2), (3), etc. to distinguish the new record from the original. This broke in `xml-editor`. 

**To Reproduce**

1. Clone a record
2. See that the cloned record has an identical name
3. Save and see the new resource still has an identical name

`edge` on left, `v7.9.3.1` on right

https://github.com/specify/specify7/assets/37256050/7e05eb17-abd9-43cb-b491-44a2f587add7

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #4517

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [x] Add relevant issue to release milestone

### Testing instructions

Clone a record
See that the cloned record has a unique name (with a (number))
Save and see the new resource still has the right name

### CODE REVIEW

File: specifyweb/frontend/js_src/lib/components/AppResources/EditorWrapper.tsx [hunk 1]
```diff
@@ -95,14 +95,14 @@ export function Wrapper({
...
-      onClone={(_clonedResource, clone): void =>
+      onClone={(clonedResource, clone): void =>
         navigate(
           formatUrl(`${baseHref}/new/`, {
             directoryKey: findAppResourceDirectoryKey(
               resourcesTree,
               directory.id
             ),
-            name: record.name,
+            name: clonedResource.name,
```
Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/components/AppResources/EditorWrapper.tsx:105]: hmm, not sure what I was thinking here.
thanks for the fix

**Review by maxpatiiuk — APPROVED** [review]

**Review by pashiav — APPROVED** [review]
Looks good! Clones with a unique name.

https://github.com/specify/specify7/assets/118556884/d27d262b-2bad-4614-b112-9a2d174cfd59

**Review by emenslin — APPROVED** [review]
Looks good, it now saves with the number at the end. 

https://github.com/specify/specify7/assets/150940840/b3cf246a-bd62-4903-b7a5-e5bb0ddc71f7
