### PR TITLE
Close resource picker on select and remove skip as an option for metadata resource in ExportFeed

### LINKED ISSUE #5000: RSS Feed visual editor allows saving without metadata resource and resource selection dialog doesn't close after selection
**Describe the bug**
Due to using the Create DwC Archive dialogs, the resource selection dialogs don't close after selecting an option (though you can see it update in the background) and lets you skip Metadata Resource.

**To Reproduce**

1. Go to App Resources
2. Create a new RSS Export Feed or open an existing one
3. Choose a DwCA Resource and choose an option
4. See that dialog does not close, but option is selected
5. Close dialog
6. Choose a Metadata Resource and choose an option
7. See that dialog does not close, but option is selected
8. Click skip
9. See that Metadata Resource is now empty
10. Save
11. Open User Tools and click Update RSS Feed
12. See that the notification is an error

**Expected behavior**
Both DwCA Resource and Metadata Resource are necessary for updating the Export Feed, so they should be required. Additionally, the dialogs should close after selecting an option, or at the very least have some more forward indication that it has been changed.

Can be separated into 2 separate issues if needed, but I put them both here due to both issues mainly being from using the Create DwC Archive dialogs.

**Screenshots**

https://github.com/specify/specify7/assets/71564869/b62f31fb-923d-4ad3-b0fc-d1d6ff8fcc78

When switching to XML editor, you can see that it requires metadata:
image

**Crash Report**

Error from notification (just says that it's missing the metadata):
[Q2VziBAF.txt](https://github.com/user-attachments/files/15808377/Q2VziBAF.txt)

- OS: Windows 10
- Browser: Firefox
- Specify 7 Version: `edge`
- Database Name: `sdnhmherps_2_8_24`
- Collection name: `Herp-PC`
- User Name: `testuser`

### PR DESCRIPTION
**Pull request by sharadsw**
Fixes #5000 

- Resource picker should now close when updating ExportFeed
- Skip is no longer an option in ExportFeed to prevent empty metadata resource
- DwCA and metadata resource fields are now required in ExportFeed

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add automated tests
- [x] Add relevant issue to release milestone

### Testing instructions

- Go to App Resources > RSS Export Feed
- Change DwCA and metadata resource
- [ ] Verify the resource picker closes on selecting a resource
- [ ] Verify metadata resource can no longer be skipped and saved without input

### CODE REVIEW

File: specifyweb/frontend/js_src/lib/components/ExportFeed/Editor.tsx [hunk 1]
```diff
@@ -330,11 +330,11 @@ function ResourcePicker({
             filters={dwcaAppResourceFilter}
             header={title}
             resources={resources}
-            skippable={type === 'metadata'}
```
Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/components/ExportFeed/Editor.tsx:333]: if `skippable` prop is no longer used here, can you check if it is still used anywhere, or else if it can be removed?

**Review by maxpatiiuk — APPROVED** [review]

File: specifyweb/frontend/js_src/lib/components/ExportFeed/Editor.tsx (hunk 1 above)
Comment (melton-jason) [reply specifyweb/frontend/js_src/lib/components/ExportFeed/Editor.tsx:333]: The `skippable` prop is still used for the `Create DwC Archive` tool. 
https://github.com/specify/specify7/blob/bb328a30a92eae17a13854356c481a5163e14759/specifyweb/frontend/js_src/lib/components/ExportFeed/Dwca.tsx#L50-L60.

Specifically, a DwC Archive can be created without an accompanying Metadata file. 

https://github.com/specify/specify7/assets/64045831/38b38c08-5825-4468-83d8-493ec3d719b0

**Review by emenslin — CHANGES_REQUESTED** [review]
### Testing instructions



- Go to App Resources > RSS Export Feed
- Change DwCA and metadata resource
- [x] Verify the resource picker closes on selecting a resource
- [ ] Verify metadata resource can no longer be skipped and saved without input

DwCA Resource and Metadata resource are not required by the visual editor but are required in the xml editor. Along with that a 404 error also briefly flashes right after you save even if you have the right resources selected


https://github.com/specify/specify7/assets/150940840/e3f27fff-6cdc-4800-b384-ca0b3e94df86

**Review by emenslin — CHANGES_REQUESTED** [review]
Same issues as above 

https://github.com/specify/specify7/assets/150940840/65120756-9501-495a-899c-2e0d8482d39f

**Review by emenslin — APPROVED** [review]
### Testing instructions



- Go to App Resources > RSS Export Feed
- Change DwCA and metadata resource
- [x] Verify the resource picker closes on selecting a resource
- [x] Verify metadata resource can no longer be skipped and saved without input

Seems like the test panel just hadn't updated before. Looks good! 

https://github.com/specify/specify7/assets/150940840/988b2672-b296-4577-a8b3-47f40be23687

**Review by Areyes42 — APPROVED** [review]
### Testing instructions

-   Go to App Resources > RSS Export Feed
-   Change DwCA and metadata resource
-  [x]  Verify the resource picker closes on selecting a resource
-   [x] Verify metadata resource can no longer be skipped and saved without input
***
Looks good, Metadata and DwCA can't be skipped, and the resource picker closes upon selection.
Screenshot 2024-06-14 at 12 34 05 PM
