### PR TITLE
uncomment apply_absolute_date

### LINKED ISSUE #7021: Querying (relative) timestampCreated for Collection Object returns all records
**Describe the bug**
When querying for collection objects based on the `timestampCreated` field in relative mode all records are returned, despite the timestamp created not falling within the designated range.

**To Reproduce**

1. Go to Query
2. Create a query with `catalogNumber` and `timestampCreated` in the CO table
3. Set the `timestampCreated` parameter to relative mode, then "Greater than or equal 1 day in the past"
4. See that all records are returned, observe that the `timeStampCreated` for records is outside of the window.
5. Set the query to some other value, such as 10 years in the past. Observe that the same number (the total number of CO in the collection) is returned.
6. As one final check, switch the `timestampCreated` filter to "any" and observe that an identical count is returned.

**Expected behavior**
Only the records that meet the criteria would be returned.

**Screenshots**
Query (sp7demofish, `v711-prerelease`)

Image

Results (sp7demofish, `v711-prerelease`)

Image

**Crash Report**

N/A

Please fill out the following information manually:
- OS: Windows 10
- Browser: Firefox 140.0.4 (64-bit)
- Specify 7 Version: `7.11-prerelease` and `7.11.0`
- Database Name: beaty and sp7demofish

**Reported By**
Beaty Biodiversity Museum

**Additional context**
I can replicate this on both sp7demofish (`v711-prerelease`) and beaty (`v7.11.0`). I initially noticed this bug because the statistics page showed an inaccurate count, shown below. **Possible 7.11.0 regression** as these statistics were behaving normally before.

Image

### PR DESCRIPTION
**Pull request by acwhite211**
Fixes #7021

Uncomment apply_absolute_date line in the execution.py file.  Looks like this line was commented out during development and needed to be added back it.  This is to fix the issue of querying for collection objects based on the timestampCreated field in relative mode all records are returned, despite the timestamp created not falling within the designated range.

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good and
      self-explanatory (or properly documented)
- [ ] Add relevant issue to release milestone
- [ ] Add pr to documentation list
- [ ] Add automated tests
- [ ] Add a reverse migration if a migration is present in the PR

### Testing instructions

- [ ] Create a specify query in the CO QB viewer.  Set the query to filter by the "Timestamp created" and set some condition on that filter.  See that the CO query results are limited and not returning all COs. 
- [ ] Go through testing instructions from: https://github.com/specify/specify7/pull/4952

### CODE REVIEW

**Review by CarolineDenis — APPROVED** [review]

**Review by emenslin — CHANGES_REQUESTED** [review]
- [x] Create a specify query in the CO QB viewer.  Set the query to filter by the "Timestamp created" and set some condition on that filter.  See that the CO query results are limited and not returning all COs. 
- [ ] Go through testing instructions from: https://github.com/specify/specify7/pull/4952

--- 

Running into a similar issue as https://github.com/specify/specify7/pull/4952#pullrequestreview-2651780490, if you check series, delete catalog number, then query series is still checked and you cannot check distinct and the count is incorrect.

https://github.com/user-attachments/assets/adea71c5-c382-4c12-8c76-02e8d2384fba



Also I was able to replicate this issue https://github.com/specify/specify7/pull/4952#pullrequestreview-2808169900 where if you check series then disable catalog number it throws an error. 

https://github.com/user-attachments/assets/f6c2cd79-5404-4415-aae9-44264cded5a2


[Specify 7 Crash Report - 2025-07-11T18_46_43.554Z.txt](https://github.com/user-attachments/files/21188757/Specify.7.Crash.Report.-.2025-07-11T18_46_43.554Z.txt)

Other than those two issues everything else looks good

**Comment by acwhite211** [comment]
The first issue of removing catalog number and rerunning the query seems to be a front-end issue where the front-end is still putting `smushed=True` in the request.  I remember that we solved this issue, so it's odd that it is happening again, I'm investigating the issue.  The second issue of unselecting the catalog number is also causing the same issue.

**Comment by acwhite211** [comment]
Thanks @emenslin, made some changes to the logic to fix that issue.  Looks like it's behaving correctly now.  Should be good now to retest, thanks.

File: specifyweb/frontend/js_src/lib/components/QueryBuilder/Wrapped.tsx [hunk 1]
```diff
@@ -575,28 +575,30 @@ function Wrapped({
                 showSeries={showSeries}
                 tableName={table.name}
                 onRunCountOnly={(): void => runQuery('count')}
-                onSubmitClick={(): void =>
+                onSubmitClick={(): void => {
+                  const canEnableSmushed = query.fields.some(
+                    (field) => field.fieldName === "catalogNumber" && field.isDisplay
```
Comment (CarolineDenis) [inline specifyweb/frontend/js_src/lib/components/QueryBuilder/Wrapped.tsx]: this wasn't needed in https://github.com/specify/specify7/pull/4952

File: specifyweb/frontend/js_src/lib/components/QueryBuilder/Wrapped.tsx [hunk 2]
```diff
@@ -233,6 +233,18 @@ function Wrapped({
       fields: getQueryFieldRecords?.(fields) ?? query.fields,
       countOnly: mode === 'count',
     });
+
+    // Handle checking if catalogNumber is present for series query
+    const queryFields = getQueryFieldRecords?.(fields) ?? query.fields;
+    const canEnableSmushed = queryFields.length === 0 || queryFields.some(
```
Comment (CarolineDenis) [inline specifyweb/frontend/js_src/lib/components/QueryBuilder/Wrapped.tsx:239]: we have a show series variable below

**Comment by acwhite211** [comment]
Thanks for noticing that @lexiclevenger! Looks like this is an issue in main and other older version of Specify.  I created a new issue https://github.com/specify/specify7/issues/7088, so we'll ignore that issue for this PR.  Thanks!
