### PR TITLE
Move down the add button in uniqueness rule config

### LINKED ISSUE #4452: configure uniqueness rule dialog add button should move once clicked
**Describe the bug**

Since moving the `Add` button in line with the unique fields list, the sizing and alignment is weird when the red minus icons appear. 
Screenshot 2024-01-23 at 8 32 39 AM

**Expected behavior**

image

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #4452

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [x] Add relevant issue to release milestone

### CODE REVIEW

File: specifyweb/frontend/js_src/lib/components/SchemaConfig/UniquenessRuleRow.tsx [hunk 1]
```diff
@@ -246,39 +246,41 @@ function ModifyUniquenessRule({
...
+                  onClick={(): void =>
+                    handleChanged({
+                      ...rule,
+                      fields: removeItem(rule.fields, index),
+                    })
+                  }
+                />
+              )}
+            </div>
             {rule.fields.length - 1 === index && (
```
Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/components/SchemaConfig/UniquenessRuleRow.tsx:284]: can this button be placed outside the `.map()` since it only needs to be rendered once?

Comment (maxpatiiuk) [reply specifyweb/frontend/js_src/lib/components/SchemaConfig/UniquenessRuleRow.tsx:284]: and that would also allow to remove the doubly-nested div here (only one div would be needed)

**Review by maxpatiiuk — CHANGES_REQUESTED** [review]

**Review by maxpatiiuk — APPROVED** [review]
