### PR TITLE
fix(FormEditor): allow for multiple form definitions

### LINKED ISSUE #4661: When configuring conditional forms or rendering, a warning is always displayed
**Describe the bug**
When using conditional rendering, there is always a warning that appears

**To Reproduce**

1. Create a Collection Object view definition
2. Add this XML section:
   ```xml
    <row>
      <cell type="label" label="fieldNumber"/>
			<cell type="field" id="fieldNumber" name="fieldNumber" uitype="text"/>
    </row>
    <row>
      <cell type="panel" coldef="100px,2px,76px" colspan="6">
        <rows>
          <!-- This view definition will be displayed in Specify 6, or if all other conditions don't match -->
          <row>
            <cell type="label" labelfor="fieldNumber"/>
            <cell type="field" id="fieldNumber" name="fieldNumber" uitype="text" readonly="true"/>
          </row>
        </rows>
        <!-- This definition will only be displayed if fieldNumber is 2 -->
        <rows condition="fieldNumber=2">
          <row>
            <cell type="label" label="Field Number is 2!" />
          </row>
        </rows>
        <!-- Condition can be in a related table. Aggregator and formatter are called automatically when necessary -->
        <!-- Can also override the column definition using the coldef attribute -->
        <rows condition="accession.accessionNumber=1111-11-11" coldef="13px,14px,15px">
          <row>
            <cell type="label" label="Accession Number is 1111-11-11!" />
          </row>
        </rows>
      </cell>
    </row>
   ```
3. See the warning:

   ```
   Expected to find at most one <rows /> child
   ```

image

`edge` (7.9.4)

### PR DESCRIPTION
**Pull request by maxpatiiuk**
Update viewSpec to say that multiple form definitions are allowed to support conditional form definitions.

Fixes #4661

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [x] Add automated tests
- [x] Add relevant issue to release milestone

### Testing instructions

- [ ] Should be able to create conditional form definitions without errors in XML editor
- [ ] Conditional form definitions should work on forms (display correct conditional form)
- [ ] [Conditional forms documentation](https://github.com/specify/specify7/wiki/Form-System#conditional-rendering) is clear and understandable

### CODE REVIEW

File: specifyweb/frontend/js_src/lib/components/FormEditor/viewSpec.ts [hunk 1]
```diff
@@ -35,15 +35,15 @@ export const formDefinitionSpec = (table: SpecifyTable | undefined) =>
       syncers.xmlChild('enableRules', 'optional'),
       syncers.maybe(syncers.object(legacyBusinessRulesSpec()))
     ),
-    rows: rows(table),
+    definitions: definitions(table),
```
Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/components/FormEditor/viewSpec.ts:38]: As a reminder, while we use viewSpec for validation in the FormEditor, it's not yet used by the forms when rendering the forms - that will definitely change once visual form editor is available.
Until then, the change to the viewSpec only affects the form editor and form editor tests - that is why conditional form rendering code didn't have to be modified, despite this key being renamed

Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/components/FormEditor/viewSpec.ts:38]: renamed `rows` to `definitions` to be less ambiguous (there is an XML child named `rows` that contains all the rows for a given definition, and there could be multiple such definitions so `rows or rows` - having the prop be called `rows` was ambiguous as to which `rows` it's referring too)

**Review by CarolineDenis — APPROVED** [review]

**Review by pashiav — APPROVED** [review]
### Testing instructions

- [X] Should be able to create conditional form definitions without errors in XML editor
- [X] Conditional form definitions should work on forms (display correct conditional form)
- [X] [Conditional forms documentation](https://github.com/specify/specify7/wiki/Form-System#conditional-rendering) is clear and understandable
---

Looks good! No warning appears.
Screen Shot 2024-03-27 at 2 34 07 PM
