### PR TITLE
Handle Disambiguation Case for Host Taxon in QB Results

### LINKED ISSUE #7436: Query Results Show Incorrect Data and Ambiguous Headers for Fields with the Same Name
### Discussed in https://github.com/specify/specify7/discussions/7435

<div type='discussions-op-text'>

<sup>Originally posted by **bhumikaguptaa** September 22, 2025</sup>
**Description of issue**

When a query is constructed to display output fields from different paths that share the same name (e.g., FullName), the query results grid displays incorrect data and uses ambiguous, non-unique column headers. The grid appears to populate all columns with the same name using the data from the first column encountered, rather than the data from their respective paths.

This causes two major issues:
- The data presented in the results is factually incorrect.
- The user cannot distinguish between the columns due to the identical headers.

**Example Use Case**
A user queries a Collection Object record where:
The determination taxon is Mesocestoides lineatus.
The host taxon is Vulpes vulpes.

**Expected Behavior**

The results grid should display two distinct columns with unique, descriptive headers and the correct corresponding data. For instance:
Column 1 Header: Determinations: Species - Full name | Data: lineatus
Column 2 Header: Host taxon: Species - Full name | Data: vulpes

**Actual Behavior**

The results grid displays two columns with identical headers, and both show the data from the first path.
Column 1 Header: Species - Full name | Data: lineatus
Column 2 Header: Species - Full name | Data: lineatus (This is incorrect)

**Solution**

The system should generate unique column aliases for the results view, perhaps by prepending a parent table or a portion of the field path to the column header. This would resolve both the data mapping error and the user-facing ambiguity.

**Reported by** 

Alexis Beck, Le Muséum d’histoire naturelle de Genève
Link to the Bold desk ticket: https://specifysoftware.bolddesk.com/agent/tickets/197</div>

### PR DESCRIPTION
**Pull request by acwhite211**
Fixes #7436

On the front-end, allow for the disambiguation between taxon and host taxon columns in the QB results.  Implement this as a special case in the `generateMappingPathPreview` function on the front-end.  This will show the column `CollectingEvent->CollectingEventAttribute->HostTaxon->Genius->FullName` to be displayed as `Host - Genus - Full name`, rather than `Genus - Full name`.  This allows the user to differentiate between other paths from Taxon.

This resolves the specific case described in the issue.  If we want a more general solution that can resolve any disambiguation between fields in the QB results, then we'll need to design a more complex solution on the front-end.  That solution would need to be different from `generateMappingPathPreview`, as it would need to have the context of all the fields in the query, and then have some way of deciding on alternative names when disambiguation as needed.

The issue on the back-end is with the query that gets generated:
```sql
SELECT
	collectionobject.`CollectionObjectID`,
	CASE
		WHEN (taxon_1.`TaxonTreeDefItemID` = 64) THEN taxon_1.`Name`
		WHEN (taxon_2.`TaxonTreeDefItemID` = 64) THEN taxon_2.`Name`
		WHEN (taxon_3.`TaxonTreeDefItemID` = 64) THEN taxon_3.`Name`
		WHEN (taxon_4.`TaxonTreeDefItemID` = 64) THEN taxon_4.`Name`
		WHEN (taxon_5.`TaxonTreeDefItemID` = 64) THEN taxon_5.`Name`
		WHEN (taxon_6.`TaxonTreeDefItemID` = 64) THEN taxon_6.`Name`
		WHEN (taxon_7.`TaxonTreeDefItemID` = 64) THEN taxon_7.`Name`
		WHEN (taxon_8.`TaxonTreeDefItemID` = 64) THEN taxon_8.`Name`
		WHEN (taxon_9.`TaxonTreeDefItemID` = 64) THEN taxon_9.`Name`
		WHEN (taxon_10.`TaxonTreeDefItemID` = 64) THEN taxon_10.`Name`
		WHEN (taxon_11.`TaxonTreeDefItemID` = 64) THEN taxon_11.`Name`
		WHEN (taxon_12.`TaxonTreeDefItemID` = 64) THEN taxon_12.`Name`
		WHEN (taxon_13.`TaxonTreeDefItemID` = 64) THEN taxon_13.`Name`
		WHEN (taxon_14.`TaxonTreeDefItemID` = 64) THEN taxon_14.`Name`
		WHEN (taxon_15.`TaxonTreeDefItemID` = 64) THEN taxon_15.`Name`
		WHEN (taxon_16.`TaxonTreeDefItemID` = 64) THEN taxon_16.`Name`
		WHEN (taxon_17.`TaxonTreeDefItemID` = 64) THEN taxon_17.`Name`
	END AS anon_1,
	CASE
		WHEN (taxon_1.`TaxonTreeDefItemID` = 64) THEN taxon_1.`Name`
		WHEN (taxon_2.`TaxonTreeDefItemID` = 64) THEN taxon_2.`Name`
		WHEN (taxon_3.`TaxonTreeDefItemID` = 64) THEN taxon_3.`Name`
		WHEN (taxon_4.`TaxonTreeDefItemID` = 64) THEN taxon_4.`Name`
		WHEN (taxon_5.`TaxonTreeDefItemID` = 64) THEN taxon_5.`Name`
		WHEN (taxon_6.`TaxonTreeDefItemID` = 64) THEN taxon_6.`Name`
		WHEN (taxon_7.`TaxonTreeDefItemID` = 64) THEN taxon_7.`Name`
		WHEN (taxon_8.`TaxonTreeDefItemID` = 64) THEN taxon_8.`Name`
		WHEN (taxon_9.`TaxonTreeDefItemID` = 64) THEN taxon_9.`Name`
		WHEN (taxon_10.`TaxonTreeDefItemID` = 64) THEN taxon_10.`Name`
		WHEN (taxon_11.`TaxonTreeDefItemID` = 64) THEN taxon_11.`Name`
		WHEN (taxon_12.`TaxonTreeDefItemID` = 64) THEN taxon_12.`Name`
		WHEN (taxon_13.`TaxonTreeDefItemID` = 64) THEN taxon_13.`Name`
		WHEN (taxon_14.`TaxonTreeDefItemID` = 64) THEN taxon_14.`Name`
		WHEN (taxon_15.`TaxonTreeDefItemID` = 64) THEN taxon_15.`Name`
		WHEN (taxon_16.`TaxonTreeDefItemID` = 64) THEN taxon_16.`Name`
		WHEN (taxon_17.`TaxonTreeDefItemID` = 64) THEN taxon_17.`Name`
	END AS anon_2
FROM
	collectionobject
LEFT OUTER JOIN determination AS determination_1 ON
	collectionobject.`CollectionObjectID` = determination_1.`CollectionObjectID`
LEFT OUTER JOIN taxon AS taxon_1 ON
	taxon_1.`TaxonID` = determination_1.`TaxonID`
LEFT OUTER JOIN taxon AS taxon_2 ON
	taxon_1.`ParentID` = taxon_2.`TaxonID`
LEFT OUTER JOIN taxon AS taxon_3 ON
	taxon_2.`ParentID` = taxon_3.`TaxonID`
LEFT OUTER JOIN taxon AS taxon_4 ON
	taxon_3.`ParentID` = taxon_4.`TaxonID`
LEFT OUTER JOIN taxon AS taxon_5 ON
	taxon_4.`ParentID` = taxon_5.`TaxonID`
LEFT OUTER JOIN taxon AS taxon_6 ON
	taxon_5.`ParentID` = taxon_6.`TaxonID`
LEFT OUTER JOIN taxon AS taxon_7 ON
	taxon_6.`ParentID` = taxon_7.`TaxonID`
LEFT OUTER JOIN taxon AS taxon_8 ON
	taxon_7.`ParentID` = taxon_8.`TaxonID`
LEFT OUTER JOIN taxon AS taxon_9 ON
	taxon_8.`ParentID` = taxon_9.`TaxonID`
LEFT OUTER JOIN taxon AS taxon_10 ON
	taxon_9.`ParentID` = taxon_10.`TaxonID`
LEFT OUTER JOIN taxon AS taxon_11 ON
	taxon_10.`ParentID` = taxon_11.`TaxonID`
LEFT OUTER JOIN taxon AS taxon_12 ON
	taxon_11.`ParentID` = taxon_12.`TaxonID`
LEFT OUTER JOIN taxon AS taxon_13 ON
	taxon_12.`ParentID` = taxon_13.`TaxonID`
LEFT OUTER JOIN taxon AS taxon_14 ON
	taxon_13.`ParentID` = taxon_14.`TaxonID`
LEFT OUTER JOIN taxon AS taxon_15 ON
	taxon_14.`ParentID` = taxon_15.`TaxonID`
LEFT OUTER JOIN taxon AS taxon_16 ON
	taxon_15.`ParentID` = taxon_16.`TaxonID`
LEFT OUTER JOIN taxon AS taxon_17 ON
	taxon_16.`ParentID` = taxon_17.`TaxonID`
LEFT OUTER JOIN collectingevent AS collectingevent_1 ON
	collectingevent_1.`CollectingEventID` = collectionobject.`CollectingEventID`
LEFT OUTER JOIN collectingeventattribute AS collectingeventattribute_1 ON
	collectingeventattribute_1.`CollectingEventAttributeID` = collectingevent_1.`CollectingEventAttributeID`
LEFT OUTER JOIN taxon AS taxon_18 ON
	taxon_18.`TaxonID` = collectingeventattribute_1.`HostTaxonID`
WHERE
	collectionobject.`CollectionID` = 4
	AND (taxon_1.`TaxonTreeDefID` IN (4)
		OR taxon_1.`TaxonTreeDefID` IS NULL
		OR taxon_18.`TaxonTreeDefID` IN (4)
			OR taxon_18.`TaxonTreeDefID` IS NULL);
```

You can see in the query that `taxon_18`, which is associated with the CollectingEventAttribute Taxon, is not used the select clause.  So, the `anon_2` alias select clause in this case should have:
```sql
WHEN (taxon_18.`TaxonTreeDefItemID` = 64) THEN taxon_18.`Name`
```

The solution is to change the join_cache key from (table, 'TreeRanks') → (start_alias, 'TreeRanks'), preventing the host branch from reusing the determination branch’s chain.  I'm investigating to make sure that this change is ok for other tree queries.

Before:
image

After:
image

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good and
      self-explanatory (or properly documented)
- [x] Add relevant issue to release milestone
- [x] Add pr to documentation list

### Testing instructions

- Open up the query builder with Collection Object as the base table.
- Add 'Species' and 'Genus' FullName fields from the path Determinations -> Taxon
- Add 'Species' and 'Genus' FullName fields from the path Collecting Event -> Collecting Event Attribute -> Host taxon
- [x] Run the query and see that the fields from the different paths are different.  The ones from 'Host Taxon' should have the 'Host' in the column name.
- [x] Find an example row in the results where the values from the taxon and host taxon are different.
- [x] Test other tree based queries to make sure that they still work correctly.

### CODE REVIEW

File: specifyweb/frontend/js_src/lib/components/WbPlanView/mappingPreview.ts [hunk 1]
```diff
@@ -171,7 +171,13 @@ export function generateMappingPathPreview(
         ? [parentTableOrTreeName, tableNameNonEmpty]
         : [tableNameNonEmpty];
 
+  // Special case for disambiguation: Host taxon under CollectionObject
+  const isHostTaxonCase =
+    baseTableName === 'CollectionObject' &&
```
Comment (melton-jason) [inline specifyweb/frontend/js_src/lib/components/WbPlanView/mappingPreview.ts]: Host taxon is technically a field through CollectingEventAttribute. 
Thus, all queries with a non CollectionObject base table to Host Taxon can have the same issue.
