### PR TITLE
Fix infinite logs of future dates not supported

### LINKED ISSUE #4060: Going to notifications triggers lots of console errors in edge
To reproduce:
1. Go to notifications (do any action which will create it)
2. See the console gets flooded with console errors (Future dates are not supported)

Likely infinite re-render issue.

Not in 7.9, so introduced recently.

Needs to be fixed before v7.9.1 gets released.

image

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #4060

### CODE REVIEW

File: specifyweb/frontend/js_src/lib/components/Molecules/DateElement.tsx [hunk 1]
```diff
@@ -34,8 +34,9 @@ export function DateElement({
     function updateRelativeDate() {
       if (date) {
         const now = new Date();
-        const timeDifference =
-          (now.getTime() - dateObject.getTime()) / MILLISECONDS;
+        const timeDifference = Math.abs(
```
Comment (maxxxxxdlp) [inline specifyweb/frontend/js_src/lib/components/Molecules/DateElement.tsx:37]: uh, that's a tricky one. good job debugging this

**Review by maxxxxxdlp — APPROVED** [review]

File: specifyweb/frontend/js_src/lib/components/Atoms/Internationalization.ts [hunk 2]
```diff
@@ -153,8 +153,7 @@ export function getRelativeDate(date: Readonly<Date>): string {
      * create a data set and see its date of creation be 5 hours into the
      * future
      */
-    // Throw new Error('Future dates are not supported');
-    console.error('Future dates are not supported');
+    // Throw new Error('Future dates are not supported'), removed console.log in issue #4051;
```
Comment (melton-jason) [inline specifyweb/frontend/js_src/lib/components/Atoms/Internationalization.ts:156]: (very optional)

```suggestion
    // Throw new Error('Future dates are not supported'), removed console.log in #4071;
```

or if #4070 is being used as the PR for fixing #4051:

```suggestion
    // Throw new Error('Future dates are not supported'), removed console.log in #4051;
```

It may be **_very slightly_** more helpful for future developers to have a link to the Pull Request over the issue. The Pull Request generally should include more information which may be immediately more helpful such as code changes, what was causing the problem, testing instructions, potential problems with code changes, etc. 
It _may_ save future developers a click if they do not need the issue for context (which is arguably rare)

**Review by grantfitzsimmons — APPROVED** [review]
No more console errors. All seems to be working well from a user point of view.

**Review by melton-jason — APPROVED** [review]
Besides the fact that this PR also fixes #4060, what is the difference between this PR and #4070?

I see #4070 has `production` as the base branch, while this has `v7.9.1-prerelease` as the base branch. 
Was the intention to merge them separately so production has the changes before  `v7.9.1-prerelease` is out, and/or is it to assess and test the impact of 2e2caa8 in a specific testing/developing environment before the changes are merged into production?
