### PR TITLE
Expand collector subform when adding new

### LINKED ISSUE #4578: Collectors subform showing up as read only
**Describe the bug**
In the collection object form when opening the collectors subform it shows up as read only fields and you have to expand to be able to type anything. 

**To Reproduce**

1. Go to collection object form
2. Click on the collectors subform 
3. See error

**Expected behavior**
The form should open up as fields that can be typed in without having to expand the form 

**Screenshots**
Edge behavior vs 7.9.3

https://github.com/specify/specify7/assets/150940840/2ca21cbe-8965-4998-ae3c-4a68812b8912

Alternatively, please fill out the following information manually:

- OS: Windows 11
- Browser: Chrome
- Specify 7 Version: edge
- Database Name: lsumzmammals9823

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #4578

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [x] Add relevant issue to release milestone

### Testing instructions

- Go to collecting event form
- Click on the collectors subform
- See that it is expanded 

Also test: 
add new prep in gift or loan
add other types of records in subview

Notes: 
with the code changes during the refactoring of IntegratedRecordSelector.tsx between 9.3 and 9.4 we had collection.add() being called twice for resources in formTable.

### CODE REVIEW

File: specifyweb/frontend/js_src/lib/components/FormSliders/IntegratedRecordSelector.tsx [hunk 1]
```diff
@@ -115,6 +115,7 @@ export function IntegratedRecordSelector({
       <RecordSelectorFromCollection
         collection={collection}
         defaultIndex={isToOne ? 0 : index}
+        formType={formType}
         isCollapsed={isCollapsed}
```
Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/components/FormSliders/IntegratedRecordSelector.tsx:119]: another small issue not caused by this PR:
you pass `isCollapsed` to RecordSelectorFromCollection, but that component does not need it (though it's in the TypeScript type)
can you please change the type to not need isCollapsed and see how that affects other places that are using the same type and might need isCollapsed

File: specifyweb/frontend/js_src/lib/components/FormSliders/RecordSelectorFromCollection.tsx [hunk 2]
```diff
@@ -103,7 +105,7 @@ export function RecordSelectorFromCollection<SCHEMA extends AnySchema>({
       const resources = isToOne ? rawResources.slice(0, 1) : rawResources;
       if (isDependent && isToOne)
         collection.related?.placeInSameHierarchy(resources[0]);
-      if (!isInteraction) collection.add(resources);
+      if (!isInteraction && formType !== 'formTable') collection.add(resources);
       handleAdd?.(resources);
```
Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/components/FormSliders/RecordSelectorFromCollection.tsx:109]: could you please refactor the code such that this component does not receive the isInteraction and formType props at all? (generally, try to reduce how many props a component receives, as that both improves maintainability of the code and improves performance due to fewer re-renders)
it should be pretty simple - just move this line that you touched:

```ts
if (!isInteraction && formType !== 'formTable') collection.add(resources);
```

into the handleAdd

File: specifyweb/frontend/js_src/lib/components/FormSliders/IntegratedRecordSelector.tsx [hunk 3]
```diff
@@ -240,7 +241,8 @@ export function IntegratedRecordSelector({
                 preHeaderButtons={collapsibleButton}
                 sortField={sortField}
                 viewName={viewName}
-                onAdd={(): void => {
+                onAdd={(resources): void => {
+                  if (!isInteraction) collection.add(resources);
```
Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/components/FormSliders/IntegratedRecordSelector.tsx:245]: can you please double-check if this line should be added here, or on line 122
(if you add it on line 122, this could would be inside the handleAdd() function, and thus also affect the  line 184)

**Review by maxpatiiuk — APPROVED** [review]
your changes look good (assuming they fix the bugs), but there are several small refactors you could make to these files while you are at it

File: specifyweb/frontend/js_src/lib/components/FormSliders/IntegratedRecordSelector.tsx (hunk 1 above)
Comment (CarolineDenis) [reply specifyweb/frontend/js_src/lib/components/FormSliders/IntegratedRecordSelector.tsx:119]: Do you mean remove the type isCollapsed from type RecordSelectorProps?

File: specifyweb/frontend/js_src/lib/components/FormSliders/IntegratedRecordSelector.tsx (hunk 3 above)
Comment (CarolineDenis) [reply specifyweb/frontend/js_src/lib/components/FormSliders/IntegratedRecordSelector.tsx:245]: Yes I do need it there.

Comment (maxpatiiuk) [reply specifyweb/frontend/js_src/lib/components/FormSliders/IntegratedRecordSelector.tsx:244]: I understand that you need it here
I am saying that if you would move this code, than it would apply in both places where handleAdd is called
can you check if this code is needed only here or in both places where handleAdd is called?

File: specifyweb/frontend/js_src/lib/components/FormSliders/IntegratedRecordSelector.tsx [hunk 4]
```diff
@@ -240,7 +240,8 @@ export function IntegratedRecordSelector({
...
                   if (typeof handleAdd === 'function') handleAdd();
                 }}
```
Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/components/FormSliders/IntegratedRecordSelector.tsx:246]: you shouldn't be calling collecion.add here as it's now part of handleAdd

```suggestion
                onAdd={handleAdd}
```

Comment (CarolineDenis) [reply specifyweb/frontend/js_src/lib/components/FormSliders/IntegratedRecordSelector.tsx:246]: the handleAdd() in the FormTableCollection props is not called from line 122 (the onAdd prop of RecordSelectorFromCollection) but from line 132 in FormTable. Hence the need to keep this here. 
https://github.com/specify/specify7/blob/9044ffc1e29eea13e1d18ccf20cad10ef5290978/specifyweb/frontend/js_src/lib/components/FormCells/FormTable.tsx#L132

Comment (CarolineDenis) [reply specifyweb/frontend/js_src/lib/components/FormSliders/IntegratedRecordSelector.tsx:246]: I tested this solution and it works for all cases it seems. (interactions, subviews, formTable, etc)

**Review by pashiav — APPROVED** [review]
Looks good! No longer appearing as read-only.

https://github.com/specify/specify7/assets/118556884/ead619b1-3606-4a4a-9b77-d91f8918bca0

**Comment by CarolineDenis** [comment]
@pashiav, 
Can you also please test the other places mentioned in the testing instructions and confirm it works there too?

**Review by pashiav — APPROVED** [review]
Confirmed it works in Gift/Loan subviews!

**Review by bronwyncombs — CHANGES_REQUESTED** [review]
Collectors subview opens as expanded grid in edit mode, but first field is not focused. This is the case for Funding agent on Collecting Trip, Authors on Reference Work, Members on Agent, so I assume this is the case for all agent subforms.  

https://github.com/specify/specify7/assets/135047322/92c9903f-50c9-4409-a946-abf7fe983728

Not sure if this is something we want to fix or not, but I know there was a change to focus first field when records open so it might be good for consistency's sake.

See andy's comment here

**Review by maxpatiiuk — APPROVED** [review]

**Review by bronwyncombs — APPROVED** [review]
Given the info in @CarolineDenis response, this is working as expected. Approve 👍
