### PR TITLE
Recompute taxonomic rank on parent change

### LINKED ISSUE #4455: Cannot add new records in trees due to 'Bad tree structure' error and cannot select a rank
**Describe the bug**
When trying to add to a tree by going through the 'edit' button there is an error and when you try to bypass it a loading screen shows up that does not finish loading 

**To Reproduce**
1. On the taxon tree click on any taxa and click 'edit'
2. Click on 'add'
3. Type in a parent and see error with the rank 
4. Click the picklist and add the next rank 
5. Save and see it loads forever 

**Expected behavior**
There should be no errors 

**Screenshots**
Beginning of the video is in edge and after the loading screen I switch to 7.9.2

https://github.com/specify/specify7/assets/150940840/141171f5-4a8e-47c2-b6ee-e4b617abf70f

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome
 - Specify 7 Version: edge 

**Database Name:** lsumzmammals, umherb_1_10_24

**Additional context**
A similar issue can be seen with the chronostrat trees in uoregonpaleo

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #4455
 and maybe #4437
Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [x] Add relevant issue to release milestone

### Testing instructions

- open data entry new taxon 
- add name 
- choose a parent of taxon that has a high rank (Acipenser)
- wait a few seconds for the taxonomic rank to be populated 
- change the taxonomic rank to the highest rank possible (Subgenus)
- change the parent taxon to a taxon that is lower in the tree than the taxonomic rank you chose (Brevirostrum)
- wait a few second for the taxonomy rank to be updated 
- save 
(examples with coldFish db) 
Please test for issue 4455 and test for 4437

### CODE REVIEW

File: specifyweb/frontend/js_src/lib/components/PickLists/TreeLevelPickList.tsx [hunk 1]
```diff
@@ -96,7 +96,11 @@ export function TreeLevelComboBox(props: DefaultComboBoxProps): JSX.Element {
                 )
               : undefined
           )
-          .then((items) => (destructorCalled ? undefined : setItems(items))),
+          .then((items) => {
+            if (destructorCalled) return undefined;
+            resource.set('definitionItem', items?.slice(-1)[0]?.value || '');
```
Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/components/PickLists/TreeLevelPickList.tsx:101]: is this essentially setting the default value?
if so take a look [at line 116 in this file](https://github.com/specify/specify7/pull/4462/files#diff-f4cb9250846063d72449e6534d14cf141a4a4ded271dfb63c02a9ffd665ef2c7R116)

```
resource.set('definitionItem', props.defaultValue ?? items?.slice(-1)[0]?.value || '');
```

(and add props.defaultValue to dependency array)
(and remove the line 116 because then it would be needless. or no? can you check?)

**Review by maxpatiiuk — CHANGES_REQUESTED** [review]

File: specifyweb/frontend/js_src/lib/components/PickLists/TreeLevelPickList.tsx [hunk 2]
```diff
@@ -96,7 +96,11 @@ export function TreeLevelComboBox(props: DefaultComboBoxProps): JSX.Element {
...
+            return void setItems(items);
```
Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/components/PickLists/TreeLevelPickList.tsx:102]: sorry about `return void`. I will disable the eslint rule that forces that (as soon as xml-editor is out)

File: specifyweb/frontend/js_src/lib/components/PickLists/TreeLevelPickList.tsx (hunk 1 above)
Comment (CarolineDenis) [reply specifyweb/frontend/js_src/lib/components/PickLists/TreeLevelPickList.tsx:101]: yep seems to work

**Review by emenslin — APPROVED** [review]
Looks good, it fixed the issues within the taxon tree and when entering taxon through data entry.

**Comment by CarolineDenis** [comment]
@emenslin, 
did you check if it was fixing https://github.com/specify/specify7/issues/4455
and https://github.com/specify/specify7/issues/4437?

**Comment by emenslin** [comment]
> @emenslin, did you check if it was fixing #4455 and #4437?

Yes it fixed both #4455 and #4437

**Comment by CarolineDenis** [comment]
@emenslin, amazing thank you!

**Review by maxpatiiuk — APPROVED** [review]

File: specifyweb/frontend/js_src/lib/components/PickLists/TreeLevelPickList.tsx [hunk 3]
```diff
@@ -96,7 +96,14 @@ export function TreeLevelComboBox(props: DefaultComboBoxProps): JSX.Element {
...
+            if (destructorCalled) return undefined;
+            resource.set(
+              'definitionItem',
+              props.defaultValue ?? (items?.slice(-1)[0]?.value || '')
+            );
+            return void setItems(items);
+          }),
       true
     );
     let destructorCalled = false;
```
Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/components/PickLists/TreeLevelPickList.tsx:109]: one last thing - you forgot to add `props.defaultValue` to the dependency array

**Review by maxpatiiuk — CHANGES_REQUESTED** [review]

**Review by pashiav — APPROVED** [review]
Fixed both https://github.com/specify/specify7/issues/4455 and https://github.com/specify/specify7/issues/4437. Looks good!

**Comment by grantfitzsimmons** [comment]
@bronwyncombs Can you test to see if this fixes #2637?

**Review by maxpatiiuk — APPROVED** [review]
