### PR TITLE
Display available/unavailable preps + allow to choose cat# in loan

### LINKED ISSUE #3397: "By Entering Cat #s" loan option not working
Selecting a set of preparations by entering the catalog number of the collection object does not add the preparations of that collection object to the loan. Instead, adds `NaN` preparations of seemingly arbitrary collection object `000008144` to loan.

https://user-images.githubusercontent.com/103299204/233736811-ee1c2a80-242b-4d03-ab84-38899da572cc.mp4

https://coldfish-edge.test.specifysystems.org/specify/view/loan/new/

### LINKED ISSUE #3453: Loan Preparations - TypeError: undefined is not iterable
**Describe the bug**
While testing Interactions- Loans. I noticed that the **Unavailable** `NaN` was intractable and not disabled like **"Available"**'s. When clicked it on. It threw the error in title. I've attached two videos and the crash reports to illustrate it.

**To Reproduce**
1. Go to Interaction - Loans in `Pripaleo`
2. Fill in `By entering PRI Catalog Numbers` with 1
3. Then click next and press **Unavailable** `NaN`

**Expected behavior**
Not interactable like **"Available"** in the video 

**Screen Recording Video**
[Specify 7 Crash Report - 2023-05-04T20_26_27.107Z (1).txt](https://github.com/specify/specify7/files/11401321/Specify.7.Crash.Report.-.2023-05-04T20_26_27.107Z.1.txt)
[Specify 7 Crash Report - 2023-05-04T20_26_27.107Z.txt](https://github.com/specify/specify7/files/11401322/Specify.7.Crash.Report.-.2023-05-04T20_26_27.107Z.txt)

https://user-images.githubusercontent.com/53784701/236323216-f1287bbc-ffc7-46f8-bf77-0f81e1ea66b1.mov

**Desktop**:
OS: Mac OSx Ventura
Browser: Chrome
Specify 7 Version: 7.8.10-prerelease

**Database Name:** Pripaleo

**Reported By:**
Carlos @carlosmbe

### LINKED ISSUE #3462: Cannot loan items in `v7.8.10`
Loan the following numbers:
`14898,15771,35657`

This looks to have been introduced in https://github.com/specify/specify7/pull/3370 – @CarolineDenis can you take a look?

`v7.8.9`:
https://vimsfish-v789.test.specifysystems.org/specify/overlay/interactions/
image

`v7.8.10`:
https://vimsfish-v7810.test.specifysystems.org/specify/overlay/interactions/
image

**Reported By:** VIMS Fish

### LINKED ISSUE #3486: Cannot create a loan "By Choosing a RecordSet"
Applies to gifts as well. Not present in `7.8.10`.

https://github.com/specify/specify7/assets/103299204/c58f73fe-8cbe-4c23-9079-597861e6d212

https://sdnhmpaleo33123-v7811-prerelease.test.specifysystems.org/specify/overlay/interactions/

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #3397
Fixes #3462
Fixes #3453 
Fixes #3486

### CODE REVIEW

**Review by maxxxxxdlp — CHANGES_REQUESTED** [review]
Looks like this bug was caused by https://github.com/specify/specify7/commit/ea4d3cf9d

The fix looks good, but I would like to request changes to the files modified in https://github.com/specify/specify7/commit/ea4d3cf9d#diff-40a25e2d48b404baea2f28c969023f392a250be25813d361099e0ce38af72145R68-R92
You check in the code if collection object id is defined. Isn't it always defined, or are the cases when it isn't?
If there are no such cases, delete the needless branch. If there are such cases, then refactor the code to remove duplication (the duplicate `<td>` and call to `syncFieldFormat`)

**Review by maxxxxxdlp — APPROVED** [review]

**Comment by CarolineDenis** [comment]
Test for: https://github.com/specify/specify7/issues/3453 too. 
Close (https://github.com/specify/specify7/issues/3453) if tests ok

**Review by grantfitzsimmons — APPROVED** [review]

File: specifyweb/frontend/js_src/lib/components/Interactions/InteractionDialog.tsx [hunk 1]
```diff
@@ -164,9 +164,11 @@ export function InteractionDialog({
       return;
     }
     const catalogNumbers = prepsData.map(([catalogNumber]) => catalogNumber);
-    const missing = catalogNumbers.filter(
-      (catalogNumber) => !entries?.includes(catalogNumber)
-    );
+    const missing = entries
```
Comment (maxxxxxdlp) [inline specifyweb/frontend/js_src/lib/components/Interactions/InteractionDialog.tsx:167]: please please don't do implicit conversion to boolean
do explicit `typeof entries === 'object'` instead to avoid bugs

**Review by maxxxxxdlp — APPROVED** [review]

**Review by carlosmbe — APPROVED** [review]

File: specifyweb/frontend/js_src/lib/components/Interactions/InteractionDialog.tsx (hunk 1 above)
Comment (maxxxxxdlp) [reply specifyweb/frontend/js_src/lib/components/Interactions/InteractionDialog.tsx:167]: given that this is high urgency pull request, @CarolineDenis please open a new pull request with the fix for this lower priority issue

please also keep the implicit vs explicit boolean comparison in mind in the future
