### PR TITLE
Display synonyms node when hovering

### LINKED ISSUE #407: Synonyms should be shown when hovering over a node in a tree
Mouse overs for synonyms are not working in both directions – mouse overs showing preferred names for a synonym are working but not mouse overs for the synonym names of preferred names.

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #407

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add automated tests
- [ ] Add relevant issue to release milestone

### Testing instructions

- go to any tree 
- hover over a node that has synonyms
- [ ] verify that the synonyms are being displayed

### CODE REVIEW

File: specifyweb/frontend/js_src/lib/components/TreeView/Row.tsx [hunk 1]
```diff
@@ -154,6 +163,33 @@ export function TreeRow({
           const stats =
             typeof nodeStats === 'object' &&
             formatTreeStats(nodeStats, row.children === 0);
+          const table = genericTables[treeName] as SpecifyTable<AnyTree>;
+          const [resource] = useLiveState<
+            SpecifyResource<AnySchema> | undefined
+          >(
+            React.useCallback(() => {
```
Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/components/TreeView/Row.tsx:170]: sorry, but you keep making the same mistake ---- you can't call react hooks anywhere but on the top level of a component
you can't call it inside of callbacks, inside of loops, inside of conditions!

please read this article carefully - https://legacy.reactjs.org/docs/hooks-rules.html#:~:text=Only%20Call%20Hooks%20at%20the%20Top%20Level
feel free to also research online how react hooks work under the hood so that you can understand why such restriction exists

Comment (maxpatiiuk) [reply specifyweb/frontend/js_src/lib/components/TreeView/Row.tsx:170]: instead, if you need some hook result to be used inside your loop, then either move the hook out of the loop, OR, if your hook relies on some data specific to that loop iteration, then move the loop body into it's own component and then inside of that component you can call your hooks at the top level

File: specifyweb/frontend/js_src/lib/components/TreeView/Row.tsx [hunk 2]
```diff
@@ -154,6 +163,33 @@ export function TreeRow({
...
+              const table = genericTables[treeName] as SpecifyTable<AnyTree>;
+              const parentNode = new table.Resource({ id: row.nodeId });
+              let node = parentNode;
+              return node;
+            }, [row.nodeId, treeName])
+          );
+          const [loadedResource] = useAsyncState(
```
Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/components/TreeView/Row.tsx:177]: performance of calling this for each row is going to be bad.
tree performance is bad as is.
instead, this information might need to be provided by the back-end, or on-demand, or enabled only for certain ranks (like we do with tree stats right now)
otherwise, this would make a lot of network requests...

cc @realVinayak

**Review by maxpatiiuk — CHANGES_REQUESTED** [review]
🔻

File: specifyweb/frontend/js_src/lib/components/TreeView/Row.tsx [hunk 3]
```diff
@@ -147,6 +157,49 @@ export function TreeRow({
...
+
+  const [fetchedChildrenName, setFetchedChildrenName] =
+    React.useState<RA<string>>();
+
+  React.useEffect(() => {
+    fetchedChildren().then(({ data: objects }) => {
+      const synonymsNames = objects.objects.map((node: Row) => node.name);
+      setFetchedChildrenName(synonymsNames);
+    });
+  }, [acceptedChildren]);
```
Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/components/TreeView/Row.tsx:201]: refactor to use useAsyncState?

File: specifyweb/frontend/js_src/lib/components/TreeView/Row.tsx [hunk 4]
```diff
@@ -147,6 +157,49 @@ export function TreeRow({
...
+        (status) =>
+          status === Http.NOT_FOUND ? unsafeTriggerNotFound() : undefined
+      );
+    }, [resource]),
+    false
+  );
+
+  const acceptedChildren = loadedResource?.get('acceptedChildren') || '';
+
+  const fetchedChildren = async (): Promise<any> => {
```
Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/components/TreeView/Row.tsx:182]: @realVinayak could you please advise if it would be better to do this on the back-end (when the rows themself are fetched) or on the front-end here (which would create a lot of extra network requests)?

File: specifyweb/frontend/js_src/lib/components/TreeView/Row.tsx [hunk 5]
```diff
@@ -147,6 +157,49 @@ export function TreeRow({
...
+        [Http.NOT_FOUND],
+        async () => resource.fetch(),
+        (status) =>
+          status === Http.NOT_FOUND ? unsafeTriggerNotFound() : undefined
+      );
+    }, [resource]),
+    false
+  );
+
+  const acceptedChildren = loadedResource?.get('acceptedChildren') || '';
```
[the remark this answers is not in the document]
Comment (maxpatiiuk) [reply specifyweb/frontend/js_src/lib/components/TreeView/Row.tsx:180]: even better, since you only need the name field, we have a `fetchRows` function that would do that even more efficiently as it would let you return just the single field you want rather than the entire resource

**Review by maxpatiiuk — CHANGES_REQUESTED** [review]

File: specifyweb/frontend/js_src/lib/components/TreeView/Row.tsx (hunk 5 above)
[the remark this answers is not in the document]
Comment (CarolineDenis) [reply specifyweb/frontend/js_src/lib/components/TreeView/Row.tsx]: after some tryouts, went for fetchCollection

**Comment by CarolineDenis** [comment]
NOTES: 
Will try to do something on the back too

**Review by maxpatiiuk — CHANGES_REQUESTED** [review]

**Review by maxpatiiuk — APPROVED** [review]
Pushed code that resolves these issues
Also, refactored fetchRows definition a bit to reduce duplication
And, added tests while I was at it

**Review by emenslin — CHANGES_REQUESTED** [review]
### Testing instructions

- go to any tree 
- hover over a node that has synonyms
- [x] verify that the synonyms are being displayed 

Looks good, when hovering it shows both synonyms and preferred taxon 
Screenshot 2024-05-08 090131
Screenshot 2024-05-08 090145

The only issue is that even when there are no synonyms for a taxon the tooltip still shows, I think if there is no synonym/preferred taxon then there shouldn't be a tooltip. 
Screenshot 2024-05-08 090427

**Review by emenslin — APPROVED** [review]
### Testing instructions

- go to any tree 
- hover over a node that has synonyms
- [x] verify that the synonyms are being displayed 

Looks good, synonym only displayed if there are actually synonyms. 
image

**Review by combs-a — APPROVED** [review]
### Testing instructions
- go to any tree 
- hover over a node that has synonyms
- [X] verify that the synonyms are being displayed 

image
image

Looking good, both hovers work.
