### PR TITLE
Remove cloning option from certain resources

### LINKED ISSUE #4809: Cloning an app resource with a visual editor does not clone the visual editor part
**Describe the bug**
Cloning any app resource that has a visual editor component (e.g. web links, record formatters) only clones the XML portion and you cannot access the visual editor. 

**To Reproduce**

1. Go to app resource
2. Click on any resource with a visual editor (e.g. web links) 
3. Click on the 'clone' or 'add' button
4. Save 
5. See there is no option to switch to visual editor 

**Expected behavior**
It should clone the entire resource and you should be able to use the visual editor 

**Screenshots**

https://github.com/specify/specify7/assets/150940840/d98bbd5a-940b-47e2-9483-a440f2d5e516

Please, also fill out the following information manually:

- OS: Windows 11
- Browser: Chrome
- Specify 7 Version: edge
- Database Name: lsumzmammals9823
- Collection name: mammals
- User Name: Spadmin
[Specify 7 System Information - 2024-04-18T19_16_36.584Z.txt](https://github.com/specify/specify7/files/15029547/Specify.7.System.Information.-.2024-04-18T19_16_36.584Z.txt)

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #4809

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add relevant issue to release milestone

### Testing instructions

- Go to app resource
- Click on any resource with a visual editor (e.g. web links)
- [ ] Verify that there is no clone option for: 

- TypeSearches
- WebLinks
- DataObjFormatters
- UIFormatters
- DataEntryTaskInit
- InteractionsTaskInit
- UserPreferences
- CollectionPreferences
- ExpressSearchConfig
- leaflet-layers

### CODE REVIEW

File: specifyweb/frontend/js_src/lib/components/Forms/Save.tsx [hunk 1]
```diff
@@ -34,6 +34,21 @@ import { FORBID_ADDING, NO_CLONE } from './ResourceView';
 
 export const saveFormUnloadProtect = formsText.unsavedFormUnloadProtect();
 
+const resourcesToNotClone = new Set([
```
Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/components/Forms/Save.tsx:37]: don't hardcode this list
instead generate it on the fly like so:
get a list of app-resources in this list that have a "name" field set to some string: https://github.com/specify/specify7/blob/3d3305bd68671e4841e3fa77c9db3c438d1615f1/specifyweb/frontend/js_src/lib/components/AppResources/types.tsx#L70

File: specifyweb/frontend/js_src/lib/components/Forms/Save.tsx [hunk 2]
```diff
@@ -192,6 +207,8 @@ export function SaveButton<SCHEMA extends AnySchema = AnySchema>({
   // Don't allow cloning the resource if it changed
   const isChanged = saveRequired || externalSaveRequired;
 
+  const cannotClone = resourcesToNotClone.has(resource.get('name') || '');
```
Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/components/Forms/Save.tsx:210]: do not pollute the Save button with random logic from different places
at very least, move this logic into the `useEnabledButtons` hook as it contains the logic for similar things

**Review by maxpatiiuk — CHANGES_REQUESTED** [review]

File: specifyweb/frontend/js_src/lib/components/Forms/Save.tsx (hunk 2 above)
Comment (maxpatiiuk) [reply specifyweb/frontend/js_src/lib/components/Forms/Save.tsx:210]: > do not pollute the Save button with random logic from different places

to clarify on this, the Save button component should be as generic as possible, able to handle all record types
if each time there is a special case in some table we add code to Save (or ResourceView), the code would become unmanageable (not to mention bug prone - what if the `name` field is present in some other table that matches your condition? - you should explicitly check for table name first)
so ideally there would be no table-specific logic, or it would be defined up in some sort of AppResource component in a way that would apply in the save button here. but if that is not easy then at very least the component-specific logic should be clearly isolated away - that's what the useEnabledButtons hook is for

**Review by lexiclevenger — CHANGES_REQUESTED** [review]
- [x] TypeSearches
- [x] WebLinks
- [x] DataObjFormatters
- [x] UIFormatters
- [x] DataEntryTaskInit
- [x] InteractionsTaskInit
- [x] CollectionPreferences
- [x] ExpressSearchConfig
- [x] leaflet-layers
- [ ] QueryFreqList
- [ ] QueryExtraList

Everything else looks good, but QueryFreqList and QueryExtraList still have the Clone button:
Screenshot 2024-05-16 at 12 27 36 PM

**Comment by CarolineDenis** [comment]
@lexiclevenger, sorry those 2 should not have been a part of the list. 
Updated it

**Review by lexiclevenger — APPROVED** [review]
### Testing instructions

- Go to app resource
- Click on any resource with a visual editor (e.g. web links)
- [x] Verify that there is no clone option for: 

- TypeSearches
- WebLinks
- DataObjFormatters
- UIFormatters
- DataEntryTaskInit
- InteractionsTaskInit
- UserPreferences
- CollectionPreferences
- ExpressSearchConfig
- leaflet-layers

---
The clone button has been removed from everything on the list now. 👍

**Review by Areyes42 — APPROVED** [review]
### Testing instructions

-   Go to app resource
    
-   Click on any resource with a visual editor (e.g. web links)
    
-   Verify that there is no clone option for:
    
-  [x] TypeSearches
    
-  [x] WebLinks
    
-  [x] DataObjFormatters
    
-  [x] UIFormatters
    
-  [x] DataEntryTaskInit
    
-  [x] InteractionsTaskInit
    
-  [x] UserPreferences
    
-  [x] CollectionPreferences
    
-  [x] ExpressSearchConfig
    
-  [x] leaflet-layers
    

* * *

Looks good! Clone button is no longer present for the listed resources.

File: specifyweb/frontend/js_src/lib/components/Forms/Save.tsx [hunk 3]
```diff
@@ -99,8 +100,10 @@ export function SaveButton<SCHEMA extends AnySchema = AnySchema>({
   const loading = React.useContext(LoadingContext);
   const [_, setFormContext] = React.useContext(FormContext);
 
+  const resourceName = resource.get('name');
   const { showClone, showCarry, showAdd } = useEnabledButtons(
-    resource.specifyTable.name
+    resource.specifyTable.name,
+    resourceName
```
[the remark this answers is not in the document]
Comment (maxpatiiuk) [reply specifyweb/frontend/js_src/lib/components/Forms/Save.tsx:106]: also, rename `resourceName` to `appResourceName` and only set that variable if resource is an app resource:

```ts
const appResourceName = resource.specifyTable.name === 'SpAppResource' ? resource.get('name') : undefined;
```

File: specifyweb/frontend/js_src/lib/components/Forms/Save.tsx [hunk 4]
```diff
@@ -320,10 +326,20 @@ function useEnabledButtons(tableName: keyof Tables): {
     'disableClone'
   );
   const [disableAdd] = userPreferences.use('form', 'preferences', 'disableAdd');
+
+  const tablesToNotClone = Object.keys(appResourceSubTypes)
+    .filter((key) => appResourceSubTypes[key].name !== undefined)
+    .map((key) => appResourceSubTypes[key]?.name!.toLowerCase());
```
Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/components/Forms/Save.tsx:332]: since this is not dependent on any variables defined in this scope, could you please move it outside this function (i.e right below it) so that we don't re-compute this on each render?

File: specifyweb/frontend/js_src/lib/components/Forms/Save.tsx [hunk 5]
```diff
@@ -320,10 +326,20 @@ function useEnabledButtons(tableName: keyof Tables): {
     'disableClone'
   );
   const [disableAdd] = userPreferences.use('form', 'preferences', 'disableAdd');
+
+  const tablesToNotClone = Object.keys(appResourceSubTypes)
```
Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/components/Forms/Save.tsx:330]: this is an incorrect variable name. did you mean `appResourcesToNotClonse`?

File: specifyweb/frontend/js_src/lib/components/Forms/Save.tsx (hunk 4 above)
Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/components/Forms/Save.tsx:332]: (optional) use filterArray instead of using `!`

```ts
  const appResourcesToNotClonse = filterArray(
    Object.keys(appResourceSubTypes)
      .map((key) => appResourceSubTypes[key]?.name?.toLowerCase())
  );
```

File: specifyweb/frontend/js_src/lib/components/Forms/Save.tsx [hunk 6]
```diff
@@ -320,10 +326,20 @@ function useEnabledButtons(tableName: keyof Tables): {
...
+    (resourceName ?? '').toLowerCase()
+  );
+
   const showCarry =
     enableCarryForward.includes(tableName) && !NO_CLONE.has(tableName);
-  const showClone =
-    !disableClone.includes(tableName) && !NO_CLONE.has(tableName);
+  const showClone = cannotClone
+    ? false
+    : !disableClone.includes(tableName) && !NO_CLONE.has(tableName);
```
Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/components/Forms/Save.tsx:342]:
```suggestion
  const showClone = !disableClone.includes(tableName) && !NO_CLONE.has(tableName) && !isDisabledCloneAppResource;
```

File: specifyweb/frontend/js_src/lib/components/Forms/Save.tsx [hunk 7]
```diff
@@ -320,10 +326,20 @@ function useEnabledButtons(tableName: keyof Tables): {
     'disableClone'
   );
   const [disableAdd] = userPreferences.use('form', 'preferences', 'disableAdd');
+
+  const tablesToNotClone = Object.keys(appResourceSubTypes)
+    .filter((key) => appResourceSubTypes[key].name !== undefined)
+    .map((key) => appResourceSubTypes[key]?.name!.toLowerCase());
+
+  const cannotClone = tablesToNotClone.includes(
```
Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/components/Forms/Save.tsx:334]: rename to `isDisabledCloneAppResource` or something more descriptive since this is only for app resources?

**Review by maxpatiiuk — CHANGES_REQUESTED** [review]

**Review by maxpatiiuk — APPROVED** [review]
👍
