### PR TITLE
Fix console error when exiting query builder

### LINKED ISSUE #3523: Console error when exiting query builder
1. Open production branch
2. Open query builder
3. Add any field
4. Open any other page
5. See an error in the console

Screenshot 2023-05-22 at 12 43 38

<details><summary>Hint</summary>
<p>

Turns out the value of `mirror` is not always of type `Element | null`.

</p>
</details> 

<details><summary>Solution</summary>
<p>

Replace:
```ts
      const mirror = (
        sortable as unknown as { readonly mirror: Element | null }
      ).mirror;
      if (mirror !== null) mirror.parentNode?.removeChild(mirror);
```
with:
```ts
      const mirror = (
        sortable as unknown as { readonly mirror?: Element | null }
      ).mirror;
      mirror?.parentNode?.removeChild(mirror);
```

</p>
</details>

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #3523

### CODE REVIEW

**Review by maxxxxxdlp — APPROVED** [review]

File: specifyweb/frontend/js_src/lib/components/QueryBuilder/Fields.tsx [hunk 1]
```diff
@@ -11,6 +11,7 @@ import { scrollIntoView } from '../TreeView/helpers';
 import type { MappingPath } from '../WbPlanView/Mapper';
 import type { QueryField } from './helpers';
 import { QueryLine } from './Line';
+import { typeOf } from 'react-is';
```
Comment (melton-jason) [inline specifyweb/frontend/js_src/lib/components/QueryBuilder/Fields.tsx:14]: Is this used anywhere in `Fields.tsx`?

Comment (melton-jason) [inline specifyweb/frontend/js_src/lib/components/QueryBuilder/Fields.tsx:14]: Is typeOf used anywhere in `Fields.tsx`?

**Review by melton-jason — CHANGES_REQUESTED** [review]

**Review by melton-jason — APPROVED** [review]
