### PR TITLE
Correct WorkBench dialog heading so 'Timestamp Modified' becomes 'Timestamp Uploaded' 

### LINKED ISSUE #4011: WorkBench Data Sets dialog shows "Timestamp Modified" instead of "Uploaded"
`v7.7.5`, `v7.8.0`:
image

`v7.9-dev`,`v7.8.13`, `v7.8.4`,:
image

Where did it all go wrong!?

### PR DESCRIPTION
**Pull request by grantfitzsimmons**
Fixes #4011

This essentially undoes the change @maxpatiiuk made in December 2022 (https://github.com/specify/specify7/commit/43cf24ded9ea95580ff69dc8833435d2c52215a0), but instead of using `commonText.uploaded`, it defines a new string consistent with the 'Timestamp' nomenclature. 

### Checklist

- [X] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add automated tests
- [X] Add relevant issue to release milestone

### Testing instructions

image

1. Open the WorkBench dialog
2. Verify that 'Timestamp Uploaded' is shown instead of 'Timestamp Created'
3. Verify sorting works correctly

### CODE REVIEW

File: specifyweb/frontend/js_src/lib/localization/workbench.ts [hunk 1]
```diff
@@ -1349,6 +1349,9 @@ export const wbText = createDictionary({
     'uk-ua': 'Набір даних',
     'de-ch': 'Datensatz',
   },
+  dataSetTimestampUploaded: {
+    'en-us': 'Timestamp Uploaded',
```
Comment (grantfitzsimmons) [inline specifyweb/frontend/js_src/lib/localization/workbench.ts:1353]: @maxpatiiuk Should this be a common string since this may be useful outside of the WorkBench? I couldn't think of another context that this could be used in yet (the batch attachment uploading tool actually shows timestamp modified, not uploaded) 

Screenshot 2024-01-26 at 9 54 16 PM

**Review by maxpatiiuk — APPROVED** [review]

**Review by realVinayak — APPROVED** [review]

**Review by pashiav — APPROVED** [review]
Looks good!
