### PR TITLE
Display date input when accessible full date off and no precision

### LINKED ISSUE #4783: Turning off "use accessible full date picker" shrinks the date input field if it doesn't have date precision
**Describe the bug**
When "use accessible full date picker" is turned off in settings, the date input field shrinks to a point where you can't read the date if it doesn't have date precision. For fields where you can add input, you still can just fine--it only affects the view.

**To Reproduce**

1. Go to Preferences
2. Turn off "Use accessible date picker"
3. Go to a form that has date fields with no date precision selection (i.e. Borrow form, most interaction forms, forms with Date Modified, and File Created Date on the Collection Object Attachments subview) 

**Expected behavior**
The date field should not shrink.

**Screenshots**
In `edge`:
image

In `v7.9.3` (expected):
image

- OS: Windows 10
- Browser: Firefox
- Specify 7 Version: `edge`
- Database Name: `sdnhm_herps_2_8_24`
- Collection name: `Herp-PC`
- User Name: `testuser`

[Specify 7 System Information - 2024-04-12T14 27 29.813Z.txt](https://github.com/specify/specify7/files/14959959/Specify.7.System.Information.-.2024-04-12T14.27.29.813Z.txt)

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #4783

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [x] Add relevant issue to release milestone

### Testing instructions

- Go to Preferences
- Turn off "Use accessible date picker"
- Go to a form that has date fields with date precision selection (CO)
- [ ] Verify that the date precision is visible 
- Go to a form that has date fields with no date precision selection (Borrow in interactions) 
- [ ] Verify that the date precision is visible 
- [ ] verify the same but with  "Use accessible date picker" on

### CODE REVIEW

**Review by bronwyncombs — APPROVED** [review]
- [X] Verify that the date precision is visible 
- Go to a form that has date fields with no date precision selection (Borrow in interactions) 
- [X] Verify that the date precision is visible 
- [X] verify the same but with  "Use accessible date picker" on 

Off: 
Screenshot 2024-04-15 at 9 44 49 AM
On: 
Screenshot 2024-04-15 at 9 47 24 AM

**Review by pashiav — APPROVED** [review]
### Testing instructions
- Go to Preferences
- Turn off "Use accessible date picker"
- Go to a form that has date fields with date precision selection (CO)
- [X] Verify that the date precision is visible 
- Go to a form that has date fields with no date precision selection (Borrow in interactions) 
- [X] Verify that the date precision is visible 
- [X] verify the same but with  "Use accessible date picker" on 
---
Looks good! Dates are viewable.
Screen Shot 2024-04-15 at 9 46 27 AM

File: specifyweb/frontend/js_src/lib/components/FormPlugins/DateInput.tsx [hunk 1]
```diff
@@ -88,6 +90,9 @@ export function DateInput({
   return (
     <>
       <Input.Generic
+        className={
+          !dateSupported && canChangePrecision ? '' : '!w-[unset] grow'
+        }
```
Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/components/FormPlugins/DateInput.tsx:95]: While this fix seems to work, I would encourage us not to introduce back complexity to PartialDateUi as it's already quite complex (and any complexity would lead to more bugs in the future)

instead, here is the solution that would involve simplifying it a bit:

take a look at this line:

https://github.com/specify/specify7/blob/d11322782d29b472296d3ac05b780820bdb41cde/specifyweb/frontend/js_src/lib/components/FormPlugins/PartialDateUi.tsx#L52

when date precision field is not visible, there is no need for `grid grid-cols-[fit-content(40%)_1fr] gap-1` - so instead of adding this condition here, with extra classes and `!`, could you just remove the grid related classes from the container?

**Review by maxpatiiuk — DISMISSED** [review]
While

**Review by melton-jason — APPROVED** [review]

**Review by maxpatiiuk — COMMENTED** [review]
👍
