### PR TITLE
Modify ResourceSelector to use existing resource instance

### LINKED ISSUE #4865: Subview is collapsed immediately when record is added
**Describe the bug**

**To Reproduce**

1. Go to https://fitznhmdoct2023-edge.test.specifysystems.org/specify/view/collectionobject/new/ as `petrifiedroadkill` in the "NHMD Danekrae" collection
2. Add a record to the Paleo Context subview
3. See that the subview is collapsed in grid view rather than open to let the user easily add data to the record

**Expected behavior**
It should work as it did in `v7.9.3.1`.

It should automatically be expanded when a new item is added to a subview in grid mode. It adds an extra click each time an item is added so it can be expanded. 

**Screenshots**
Left is `v7` (expected behavior), right is `edge` (bug)

https://github.com/specify/specify7/assets/37256050/b5d68f9a-8b1e-4eb6-9c62-c89f2e5b44b4

https://fitznhmdoct2023-edge.test.specifysystems.org/specify/view/collectionobject/new/
https://fitznhmdoct2023-v7.test.specifysystems.org/specify/view/collectionobject/4371987/

**System Information**
[Specify 7 System Information - 2024-05-01T16_09_51.048Z.txt](https://github.com/specify/specify7/files/15178896/Specify.7.System.Information.-.2024-05-01T16_09_51.048Z.txt)

**Database:** Fitz_NHMD_Oct_2023
**Username:** petrifiedroadkill
**Collection:** NHMD Danekrae

### PR DESCRIPTION
**Pull request by sharadsw**
Fixes #4865 

When adding a form table subview, 2 resources were being created. 

First one in `FormTable.tsx`: https://github.com/specify/specify7/blob/907d1524cfbc56380fc038b0f7a3663e7ff46576/specifyweb/frontend/js_src/lib/components/FormCells/FormTable.tsx#L458-L459

Which gets set as an expanded record and gets passed up the parent chain:
https://github.com/specify/specify7/blob/907d1524cfbc56380fc038b0f7a3663e7ff46576/specifyweb/frontend/js_src/lib/components/FormCells/FormTable.tsx#L125-L132

But that resource instance gets lost in `RecordSelector.tsx`, which creates a new resource that does not get added to expandedRecords and gets passed all the way up to `SubView.tsx`
https://github.com/specify/specify7/blob/907d1524cfbc56380fc038b0f7a3663e7ff46576/specifyweb/frontend/js_src/lib/components/FormSliders/RecordSelector.tsx#L128-L134

My change ensures RecordSelector uses the resource initialized by a child component.

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add automated tests
- [x] Add relevant issue to release milestone

### Testing instructions

**For to-one relations**:
- Use a Paleo database
- Go to Data Entry -> Collection Object
- Add a PaleoContext
  - [ ] Verify the PaleoContext subview is not collapsed by default
  - [ ] Verify data can be saved in the subview and persists on refresh
- [ ] Additionally, verify other subviews in the form still work like they used to

**For interactions**:
- Click on Interactions -> Gift
- Add a gift preparation 
- Click on add unassociated item
  - [ ] Verify subview is not collapsed by default
- Add another gift preparation by using a record set with no preparations
  - [ ] Verify subview is not collapsed by default

### CODE REVIEW

File: specifyweb/frontend/js_src/lib/components/FormSliders/IntegratedRecordSelector.tsx [hunk 1]
```diff
@@ -180,7 +180,9 @@ export function IntegratedRecordSelector({
                         }
                         onClick={(): void => {
                           focusFirstField();
-                          handleAdd();
+                          const resource =
+                            new collection.table.specifyTable.Resource();
+                          handleAdd([resource]);
```
Comment (CarolineDenis) [inline specifyweb/frontend/js_src/lib/components/FormSliders/IntegratedRecordSelector.tsx:185]: do we have to keep the resource as an array?

**Review by melton-jason — APPROVED** [review]
Nice debugging work! 

If any table besides PaleoContext is to be tested, #4865 should have occurred with any `to-one` relationship which could be rendered as a SubView. 

Here are the (non-system) table names with the names of the relationships for which #4865 should have occurred with: 

```json
{
   "Accession":[
      "addressOfRecord"
   ],
   "Borrow":[
      "addressOfRecord"
   ],
   "CollectingEvent":[
      "collectingEventAttribute"
   ],
   "CollectingTrip":[
      "collectingTripAttribute"
   ],
   "CollectionObject":[
      "collectionObjectAttribute",
      "paleoContext"
   ],
   "ExchangeIn":[
      "addressOfRecord"
   ],
   "ExchangeOut":[
      "addressOfRecord"
   ],
   "Loan":[
      "addressOfRecord"
   ],
   "Preparation":[
      "preparationAttribute"
   ],
   "RepositoryAgreement":[
      "addressOfRecord"
   ],
   "Taxon":[
      "taxonAttribute"
   ]
}
```

File: specifyweb/frontend/js_src/lib/components/FormSliders/IntegratedRecordSelector.tsx (hunk 1 above)
Comment (sharadsw) [reply specifyweb/frontend/js_src/lib/components/FormSliders/IntegratedRecordSelector.tsx:185]: For `IntegratedRecordSelector` and its children, I can't seem to find any case where `resources` needs to be an array. The only time it is treated as an array is here:
https://github.com/specify/specify7/blob/71ad206747904a98fac6043116e2c05331f5036c/specifyweb/frontend/js_src/lib/components/FormCells/FormTable.tsx#L125-L130
and even there it only ever has 1 element.

I'm not sure, I think converting it to a single resource instead of an array does make it less confusing. But there could be a case made for leaving it as an array to keep things consistent with other parts of the code.

**Review by maxpatiiuk — APPROVED** [review]

**Review by CarolineDenis — APPROVED** [review]

**Review by CarolineDenis — APPROVED** [review]

File: specifyweb/frontend/js_src/lib/components/Interactions/InteractionDialog.tsx [hunk 2]
```diff
@@ -282,7 +287,11 @@ export function InteractionDialog({
                   <Button.Info
                     onClick={(): void => {
                       itemCollection?.add(
-                        new itemCollection.table.specifyTable.Resource()
+                        (interactionResource as SpecifyResource<
```
[the remark this answers is not in the document]
Comment (sharadsw) [reply specifyweb/frontend/js_src/lib/components/Interactions/InteractionDialog.tsx]: Created a function for adding the resource to `itemCollection` to reduce duplication

File: specifyweb/frontend/js_src/lib/components/FormSliders/IntegratedRecordSelector.tsx [hunk 3]
```diff
@@ -243,7 +252,7 @@ export function IntegratedRecordSelector({
                 viewName={viewName}
                 onAdd={(resources): void => {
                   if (!isInteraction) collection.add(resources);
-                  if (typeof handleAdd === 'function') handleAdd();
+                  if (typeof handleAdd === 'function') handleAdd(resources);
```
Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/components/FormSliders/IntegratedRecordSelector.tsx:255]: (optional)
```suggestion
                  handleAdd?.(resources);
```

**Review by maxpatiiuk — APPROVED** [review]

**Review by acwhite211 — APPROVED** [review]
