### PR TITLE
Fix spelling mistake in leaving dialog

### LINKED ISSUE #4453: Uniqueness rules configuration: spelling error in leave w/o save confirm dialog
**Describe the bug**

"your" --> "you"
also maybe "would" should be "will"?

Screenshot 2024-01-23 at 8 41 46 AM

**To Reproduce**
1. Go to schema config>uniqueness rules
2. add uniqueness rule
3. click close without saving

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #4453

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [x] Add relevant issue to release milestone

### Testing instructions

Go to schema config>uniqueness rules
add uniqueness rule
click close without saving
See correct spelling of 'Unsaved changes would be lost if you leave this page.'

### CODE REVIEW

**Review by pashiav — APPROVED** [review]
Looks good!
issue-4453

**Review by grantfitzsimmons — APPROVED** [review]

File: specifyweb/frontend/js_src/lib/localization/main.ts [hunk 1]
```diff
@@ -231,19 +231,7 @@ export const mainText = createDictionary({
     'de-ch': 'Sind Sie sicher, dass Sie diese Seite verlassen wollen?',
   },
   leavePageConfirmationDescription: {
-    'en-us': 'Unsaved changes would be lost if your leave this page.',
```
Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/localization/main.ts:234]: why where the other languages removed?
(the translations looked a good)

also, when en string changes, weblate automatically flags other strings for manual review (and shows to translators how the en string changes, so you certainly don't need to remove the strings in the code

---

and, the original issue mentioned:

> also maybe "would" should be "will"?

is that something we should change?

@grantfitzsimmons

**Review by maxpatiiuk — CHANGES_REQUESTED** [review]

**Review by maxpatiiuk — APPROVED** [review]
