### PR TITLE
Remove unecessary skeleton loader from QueryListDialog

### LINKED ISSUE #4518: Statistics page shows extra queries dialog while loading queries
**To Reproduce**

1. Go to the stats page
2. Go to add a new query (click **Add**) in the bottom right corner of a category
3. See an extra queries dialog appear while the queries are loaded
4. Once they have loaded, see that it disappears

**Expected behavior**
There should only be one dialog

**Screenshots**
image

https://github.com/specify/specify7/assets/37256050/cd49431f-50cd-4726-9b25-271e465f789f

`edge` on left, `v7.9.3.1` on right

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #4518

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [x] Add relevant issue to release milestone

### Testing instructions

Go to the stats page
Go to add a new query (click Add) in the bottom right corner of a category
See that there isn't an extra queries dialog appear while the queries are loaded

NOTES: 
Since the refactoring of QueryListDialog component the skeleton loader is not necessary anymore.

### CODE REVIEW

File: specifyweb/frontend/js_src/lib/components/Toolbar/Query.tsx [hunk 1]
```diff
@@ -125,101 +124,90 @@ export function QueryListDialog({
 
   const isReadOnly = React.useContext(ReadOnlyContext);
 
-  return data === undefined ? (
-    <Dialog
```
Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/components/Toolbar/Query.tsx:129]: isn't this still needed for the other places where QueryListDialog is used though?
so instead of removing it, could you instead move it into the `defaultChildren` function?

Comment (CarolineDenis) [reply specifyweb/frontend/js_src/lib/components/Toolbar/Query.tsx:129]: I added the skeleton in the default children but not sure that's what you meant

Comment (maxpatiiuk) [reply specifyweb/frontend/js_src/lib/components/Toolbar/Query.tsx:129]: yes, that's what I meant - thanks

this way, by default, consumers of this component still get a loader, but they don't get a bug if they choose to provide a custom `children` function

**Review by maxpatiiuk — APPROVED** [review]

**Review by emenslin — APPROVED** [review]
Looks good, no more skeleton loader. 

https://github.com/specify/specify7/assets/150940840/e4e2a4d7-e9f6-4ad7-a60d-9f52ef383278

**Review by bronwyncombs — APPROVED** [review]
Working as expected! 
This branch vs `edge` on the right: 

https://github.com/specify/specify7/assets/135047322/c8f2e12a-0004-40c9-b6a6-31898579c6fe
