### PR TITLE
Dissable browse to form when no results

### LINKED ISSUE #3796: Query builder from QCB doesn't disable Browse in Forms when 0 results returned
**Describe the bug**
The query builder dialog that's accessed from a query combo box allows to select `Browse in Forms` even when 0 results are returned. Upon click an infinite loading dialog begins. 

**To Reproduce**
1. Go to record with query combo box
2. Click on magnifying glass icon to the right
3. Click on `Query Builder`
4. Run a query that returns no results
5. Select `Browse in Forms`
6. See error

**Screenshots**

https://github.com/specify/specify7/assets/135047322/331885a0-cdec-4c0b-9c28-60419bdd99c8

https://github.com/specify/specify7/assets/135047322/1287d789-8f2d-448a-b778-81ce042f8980

**Desktop:**
 - macOS, Chrome, `v7.9-dev`
 
**Database Name:** sdnhmpaleo

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #3796

### CODE REVIEW

**Comment by maxxxxxdlp** [comment]
Wow, this pull request has 0 code changes - I didn't know that was possible!

**Comment by CarolineDenis** [comment]
@bronwyncombs or @carlosmbe could yo test this to see if it's satisfying? 
@melton-jason what do you think of adding that condition?

**Review by bronwyncombs — APPROVED** [review]
Working for me! `Browse in Forms` option is not available for queries without results. Tested multiple tables and fields. Tested embedded query and query builder.

File: specifyweb/frontend/js_src/lib/components/QueryBuilder/Results.tsx [hunk 1]
```diff
@@ -202,7 +202,7 @@ export function QueryResults(props: Props): JSX.Element {
         Array.isArray(results) &&
         Array.isArray(loadedResults) &&
         results.length > 0 &&
-        typeof fetchResults === 'function' ? (
+        typeof fetchResults === 'function' && totalCount !== 0 ? (
```
Comment (maxxxxxdlp) [inline specifyweb/frontend/js_src/lib/components/QueryBuilder/Results.tsx:205]: how is `totalCount !== 0` different from the `results.length > 0` condition that was already here (one line above)?

only one of those should be needed, unless something fishy is going on here - can you investigate? @CarolineDenis

**Review by maxxxxxdlp — CHANGES_REQUESTED** [review]

File: specifyweb/frontend/js_src/lib/components/QueryBuilder/Results.tsx (hunk 1 above)
Comment (CarolineDenis) [reply specifyweb/frontend/js_src/lib/components/QueryBuilder/Results.tsx:205]: because sometimes results = [undefined] instead of []

Comment (CarolineDenis) [reply specifyweb/frontend/js_src/lib/components/QueryBuilder/Results.tsx:205]: I'm looking into it now... 
handleSetResults is being with results=undefined and it shouldn't be called at all

Comment (CarolineDenis) [reply specifyweb/frontend/js_src/lib/components/QueryBuilder/Results.tsx:205]: seems to work every time

Comment (maxxxxxdlp) [reply specifyweb/frontend/js_src/lib/components/QueryBuilder/Results.tsx]: good catch - thanks for resolving this issue the proper way rather than adding a hack

**Review by maxxxxxdlp — APPROVED** [review]
thanks for resolving this issue the proper way rather than adding a hack
