### PR TITLE
Fix: rename view definition dialog title to 'New View Definition'

### LINKED ISSUE #5052: Dialog for naming a view definition is called "Form Definition"
**Describe the bug**
When creating a new view definition, the dialog that prompts the user to name the view definition is called "Form Definition."

**To Reproduce**

1. Go to an existing form definition, or make a new one
2. Choose a table. Then, click "Create" to add a view definition
3. Click "New"
4. See that the dialog is called "Form Definition"

**Expected behavior**
The dialog for naming a form definition is called "New Form Definition." 
Screenshot 2024-06-27 at 11 33 48 AM

For consistency, the dialog for naming a view definition should be called "New View Definition" instead of "Form Definition."

**Screenshots**

https://github.com/specify/specify7/assets/164079735/aebd1ef2-1cfd-41ab-9925-736f019baed5

[Specify 7 System Information - 2024-06-27T16_38_41.413Z.txt](https://github.com/user-attachments/files/16018283/Specify.7.System.Information.-.2024-06-27T16_38_41.413Z.txt)

Please, also fill out the following information manually:

- OS: Mac
- Browser: Chrome
- Specify 7 Version: 7.9.4 through edge
- Database Name: KU_Fish_Tissue_2024_01_24
- Collection name: KU Fish Observation Collection
- User Name: spfishadmin

### PR DESCRIPTION
**Pull request by Gitesh307**
Fixes #5052

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good and
      self-explanatory (or properly documented)
- [x] Add relevant issue to release milestone

### Testing instructions

- Open the Test Panel in Specify and select any database
- Create a new View Definition (choose a table(App Resources) → click Create → New).
- [x] Verify the dialog title now reads “New View Definition” instead of “Form Definition.”

### CODE REVIEW

**Review by CarolineDenis — APPROVED** [review]

File: specifyweb/frontend/js_src/lib/components/AppResources/Create.tsx [hunk 1]
```diff
@@ -283,7 +285,7 @@ function EditAppResource({
       title={
         type.tableName === 'SpViewSetObj'
           ? formsText.newResourceTitle({
-              tableName: resourcesText.formDefinition(),
+              tableName: resourcesText.newViewDefinition(),
```
Comment (CarolineDenis) [inline specifyweb/frontend/js_src/lib/components/AppResources/Create.tsx:288]: Find out where this is displayed in the UI and look at the rendering after your changes. You can paste a screen shot in a comment here.

Comment (Gitesh307) [reply specifyweb/frontend/js_src/lib/components/AppResources/Create.tsx:288]: App_Resource

This part is getting displayed under App Resources Form Definition. Will revert the changes for this file.

**Review by acwhite211 — APPROVED** [review]

**Review by lexiclevenger — APPROVED** [review]
- [x] Verify the dialog title now reads “New View Definition” instead of “Form Definition.”
---
Looks good!
Screenshot 2025-08-29 at 12 23 45 PM
