### PR TITLE
Set domainFilter to false to avoid Hierarchy exception

### LINKED ISSUE #3564: `xml-editor`: Hierarchy Exception when defining formatters and aggregators for some tables.
**Describe the bug**
The backend raises a Hierarchy Exception when defining formatters and aggregators for some tables. Need to do more digging into what the cause is. 

**To Reproduce**
1. Go to the visual editor for defining formatters and aggregators.
2. Go to either Formatters menu or the Aggregators menu.
3. Click on table 'Appraisal' and then click on 'Add'

**Expected behavior**
It shouldn't crash and allow to make formatters / aggregators

**Screenshots**
image

Also: HierarchyException when choosing a table on the web link form

Describe the bug
When choosing a table for a web link, a HierarchyException occurs

HierarchyException at /api/specify/agentidentifier/ queryset model Agentidentifier has no hierarchy field 
To Reproduce

Go to a 'WebLinks' app resource
Edit a web link by choosing one from the list (or create a new one)
Choose the 'Agent Identifier' table as a base
See error appear
Screen Recording
https://github.com/specify/specify7/assets/37256050/bae92ea3-323e-4c3e-a0f9-0e9930b0fc3f

[Specify 7 Crash Report - 2023-12-05T15_21_29.112Z.txt](https://github.com/specify/specify7/files/13561952/Specify.7.Crash.Report.-.2023-12-05T15_21_29.112Z.txt)

Also: Creating a new formatter for AccessionCitation throws an error

image
https://kufish51623-issue-3565.test.specifysystems.org/specify/resources/app-resource/9/formatter/AccessionCitation/58

[Specify 7 Crash Report - 2023-10-24T01_18_54.997Z.txt](https://github.com/specify/specify7/files/13096897/Specify.7.Crash.Report.-.2023-10-24T01_18_54.997Z.txt)

Encountered when testing https://github.com/specify/specify7/pull/4114

### PR DESCRIPTION
**Pull request by acwhite211**
Fixes #3564

This is a temporary fix to stay on schedule for releasing the xml editor.  Fixing the filter_by_col function on the back-end needs to be done.  The #4498 PR is an attempt at that, but at this time needs more work.  As discussed on the issue page, setting the domain filter to false will avoid the Hierarchy exception from being thrown for tables without direct collection table relations.

Look at the #3564 issue for testing instructions.

### CODE REVIEW

File: specifyweb/frontend/js_src/lib/components/Formatters/Preview.tsx [hunk 1]
```diff
@@ -36,7 +36,7 @@ export function useResourcePreview(table: SpecifyTable): {
           table.name,
           {
             limit: defaultPreviewSize,
-            domainFilter: true,
+            domainFilter: false, // set to true after scoping reimplementation
```
Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/components/Formatters/Preview.tsx:39]: can this be turned into a todo comment so that it's less likely to get lost?
as per https://github.com/specify/specify7/tree/production/specifyweb/frontend/js_src/lib#todos, BUG or REFACTOR types work best here

```suggestion
            domainFilter: false, // REFACTOR: set to true after scoping reimplementation
```

**Review by maxpatiiuk — APPROVED** [review]

**Review by CarolineDenis — APPROVED** [review]

File: specifyweb/frontend/js_src/lib/components/Formatters/Preview.tsx (hunk 1 above)
Comment (acwhite211) [reply specifyweb/frontend/js_src/lib/components/Formatters/Preview.tsx]: ya, that's a good idea

**Review by pashiav — APPROVED** [review]
Looks good! No errors when testing.
