### PR TITLE
Fix scroll bar when exporting to TSV 

### LINKED ISSUE #2733: `statspage`: Scrollbar appears when exporting to TSV
https://user-images.githubusercontent.com/37256050/210431469-a27ec23d-70a2-4608-8735-00be052f8f60.mov

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes  #2733

### CODE REVIEW

**Review by grantfitzsimmons — CHANGES_REQUESTED** [review]
https://user-images.githubusercontent.com/37256050/229659718-223d4e01-f754-4b5f-b637-009eb7da8ffb.mov

I still see the issue

https://herbrbge33123-issue-2733.test.specifysystems.org/specify/stats

Firefox, macOS

**Comment by CarolineDenis** [comment]
@grantfitzsimmons can you test this to see if it makes any difference?

File: specifyweb/frontend/js_src/lib/components/Molecules/FilePicker.tsx [hunk 1]
```diff
@@ -140,6 +140,7 @@ export const downloadFile = async (
 ): Promise<void> =>
   new Promise((resolve) => {
     const iframe = document.createElement('iframe');
+    iframe.classList.add('absolute', 'hidden');
```
Comment (maxxxxxdlp) [inline specifyweb/frontend/js_src/lib/components/Molecules/FilePicker.tsx:143]: I was hesitant to add `'hidden'` as some browsers might not trigger file downloads from hidden iframes.
Just adding `absolute` might be sufficient to fix this issue.

Comment (maxxxxxdlp) [reply specifyweb/frontend/js_src/lib/components/Molecules/FilePicker.tsx:143]: `'hidden'` only affects visibility, not the placement. Presence or absence of scroll bar should not be affected by it.

Doesn't the scroll bar disappear as soon as you add `'absolute'`? If not, you might need to add `top-0` or something like that

**Comment by CarolineDenis** [comment]
@maxxxxxdlp 
With absolute + hidden: 

https://user-images.githubusercontent.com/108160931/230107942-38d887b4-a1fc-4f30-b138-a0a095545454.mov

with absolute: 
Screenshot 2023-03-30 at 2 36 26 PM

File: specifyweb/frontend/js_src/lib/components/Molecules/FilePicker.tsx (hunk 1 above)
Comment (maxxxxxdlp) [reply specifyweb/frontend/js_src/lib/components/Molecules/FilePicker.tsx:143]: the 2nd video in your comment doesn't load for me, but I trust you

Interesting that there is not a single mention of scroll bars on the wiki page for visibility:hidden - https://developer.mozilla.org/en-US/docs/Web/CSS/visibility

**Review by maxxxxxdlp — APPROVED** [review]

File: specifyweb/frontend/js_src/lib/components/Molecules/FilePicker.tsx (hunk 1 above)
Comment (maxxxxxdlp) [reply specifyweb/frontend/js_src/lib/components/Molecules/FilePicker.tsx:143]: keep the hidden. as otherwise there is no point in these changes if they don't fix the scroll bar

**Review by grantfitzsimmons — APPROVED** [review]
