### PR TITLE
Handle case where tree definition doesn't exist for a tree

### LINKED ISSUE #5264: Clicking `Trees` in nav bar causes error
**Describe the bug**
On the database `um_herb_1_10_24` on branch `edge`, clicking **Trees** in the navigation bar to display the overlay causes an error. Does not seem to occur on any other database.

Tree functionalities are working as expected, but the overlay is not. You can go to https://umherb11024-edge.test.specifysystems.org/specify/tree/taxon or any other tree in the collection and see that it is working as normal.

**Notes**:
- No error occurs on branch `v7.9.6.2`, so it may have been caused by a merged branch after that release.
- Migrations have been run. I cleared my cache both through Specify and the browser, but the error still occurs.

**To Reproduce**
1. Go to `um_herb_1_10_24` on `edge` (https://umherb11024-edge.test.specifysystems.org/specify/)
2. Click on **Trees**
3. See error

**Expected behavior**
The Trees overlay should appear on-click. 

`v7.9.6.2`

https://github.com/user-attachments/assets/ba1e3605-99b4-4268-91d3-5e8627372696

**Evidence**
`edge`

https://github.com/user-attachments/assets/03df1aa1-6928-4251-8434-dd72c2994b19

**Crash Report**
[Specify 7 Crash Report - 2024-09-10T15_45_17.969Z.txt](https://github.com/user-attachments/files/16947677/Specify.7.Crash.Report.-.2024-09-10T15_45_17.969Z.txt)

OS: macOS Monterey (12.7.2)
Browser: Chrome
Specify 7 Version: `edge`
Database Name: `umherb_1_10_24`
[Specify 7 System Information - 2024-09-10T16_04_38.430Z.txt](https://github.com/user-attachments/files/16947692/Specify.7.System.Information.-.2024-09-10T16_04_38.430Z.txt)

### PR DESCRIPTION
**Pull request by sharadsw**
Fixes #5264

The frontend assumed that each tree has at least one tree definition. It looks like some dbs haven't been migrated correctly due to which their Storage trees do not have a tree definition anymore. This caused the frontend to read undefined for Storage trees and leads to the error found in the issue. This PR allows the tree selection dialog to still open even when a tree does not have a definition and avoid the error. However, we would have to manually fix the migration for the dbs where this error occurs to fix Storage trees for that db

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add automated tests
- [ ] Add relevant issue to release milestone

### Testing instructions

- Use a db where the issue occurred (`um_herb_1_10_24`, `ojsmnh11024`)
- Click on trees in the nav bar
- [ ] Verify the tree selection dialog opens and there is no error

### CODE REVIEW

**Review by CarolineDenis — APPROVED** [review]

File: specifyweb/frontend/js_src/lib/components/Toolbar/TreeRepair.tsx [hunk 1]
```diff
@@ -75,10 +75,12 @@ export function TreeSelectDialog({
...
-              const treeDefinition = deserializeResource(
-                getTreeDefinitions(treeName)[0].definition
-              );
-              return [treeName, treeDefinition] as const;
+              const treeDefinitions = getTreeDefinitions(treeName);
+              const defaultTreeDefinition =
+                treeDefinitions.length > 0
+                  ? deserializeResource(treeDefinitions[0].definition)
+                  : undefined;
+              return [treeName, defaultTreeDefinition] as const;
```
Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/components/Toolbar/TreeRepair.tsx:83]: (optional) print console.warn if there are no tree definitions for a given tree?
such console log messages will appear in the crash reports so could be useful of some bugs occur because tree defs are missing - though if we are already including tree defs in the crash reports, then this would be redundant.

**Review by maxpatiiuk — APPROVED** [review]

**Review by emenslin — APPROVED** [review]
### Testing instructions



- Use a db where the issue occurred (`um_herb_1_10_24`, `ojsmnh11024`)
- Click on trees in the nav bar
- [x] Verify the tree selection dialog opens and there is no error

Checked a couple dbs and the error is no longer thrown

**Review by Areyes42 — APPROVED** [review]
### Testing instructions

-   Use a db where the issue occurred (`um_herb_1_10_24`, `ojsmnh11024`)
-   Click on trees in the nav bar
-   [x] Verify the tree selection dialog opens and there is no error
***
Other than the migration issues with the storage trees, dialog and the other trees look good!
