### PR TITLE
Fix: Disable manual typing in tree-level rank picklists

### LINKED ISSUE #4985: Rank picklists can be typed into
**Describe the bug**
Taxonomic and Geographic rank picklists can be typed into, and sometimes stop autofilling with an appropriate rank. It is, however, appropriately blocked w/ a save blocker. You can only access the dropdown by clicking on the arrow on the right of the box.

**To Reproduce**

1. Go to Data Entry -> Taxon or Geography
2. Add a name
3. Add a parent
4. Click on picklist and type
5. See error

**Expected behavior**
You should not be able to type into the picklist.

**Screenshots**

https://github.com/specify/specify7/assets/71564869/f36148bb-81cb-4711-8bf0-66f30cd1cefc

- OS: Windows 10
- Browser: Firefox
- Specify 7 Version: `edge` (versions down to `v7.9.4` were tested as well)
- Database Name: `sdnhm_herps_2_8_24`
- Collection name: `Herp-PC`
- User Name: `testuser`

**Additional context**
Other picklists are fine, it seems to be the picklists that are auto-filled by something. When you click out of the picklist after typing an invalid rank, it clears the field but does not reset the rank.

### PR DESCRIPTION
**Pull request by Gitesh307**
Fixes #4985

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good and
      self-explanatory (or properly documented)
- [ ] Add relevant issue to release milestone

### Testing instructions
-  Go to the data entry and select Taxon/Geography.
- [ ] Check that rank picklists (e.g. Taxonomic/Geographic levels) are not typeable.
- [ ] Check other picklists (Locality ) still use AutoComplete (type-to-search).

### CODE REVIEW

File: specifyweb/frontend/js_src/lib/components/PickLists/index.tsx [hunk 1]
```diff
@@ -30,166 +27,180 @@ export function PickListComboBox({
...
-
+  const fieldNameForForm = pickList?.get('name') ?? pickListName;
   const isReadOnly = React.useContext(ReadOnlyContext);
+
+  const isRankOrTreeLevelPickList = React.useMemo(() => {
+    const identifierText = [pickList?.get?.('name'), pickListName, (field as any)?.name]
+      .filter(Boolean)
+      .join(' ')
+      .toLowerCase();
+    return /(rank|taxon.*level|geo.*level|_treelevelcombobox)/i.test(identifierText);
```
Comment (grantfitzsimmons) [inline specifyweb/frontend/js_src/lib/components/PickLists/index.tsx:173]: Why not just render all special pick lists as read-only?

https://github.com/specify/specify7/pull/7400/files#diff-6bae6d2d398090d7c917d80ff60ef98c9c15e765669841b5a2b150069acf8e53R166

See
https://github.com/specify/specify7/blob/b45cef28f3c8a5109ee132f8c26a18b78d020f52/specifyweb/frontend/js_src/lib/components/FormFields/ComboBox.tsx#L40-L45

Comment (grantfitzsimmons) [reply specifyweb/frontend/js_src/lib/components/PickLists/index.tsx:173]: See this PR: https://github.com/specify/specify7/pull/7400

**Review by grantfitzsimmons — CHANGES_REQUESTED** [review]

**Review by acwhite211 — APPROVED** [review]
