### PR TITLE
Filter out unmapped field in formatter editor 

### LINKED ISSUE #4747: Can save unmapped field in table formats
**Describe the bug**
Table formats allows you to add a field and save without it being mapped to anything. This causes an error to occur anytime you use a querycombobox with that table 

**To Reproduce**

1. Go to record formatters (through app resources or schema config) 
2. Click on accession
3. Click on the default format and add field 
4. Save without mapping a field to it 
5. Go to data entry -> Collection Object 
6. Use the accession querycombobox 
7. See error  

**Expected behavior**
There should be a save blocker that doesn't let you save an unmapped field

**Screenshots**

https://github.com/specify/specify7/assets/150940840/8714b2ae-3bf1-465a-9083-f73794e4e1b5

**Crash Report**
[Specify 7 Crash Report - 2024-04-05T17_20_08.944Z.txt](https://github.com/specify/specify7/files/14888404/Specify.7.Crash.Report.-.2024-04-05T17_20_08.944Z.txt)

Please, also fill out the following information manually:

- OS: Windows 11
- Browser: Chrome
- Specify 7 Version: edge
- Database Name: lsumzmammals9823
- Collection name: mammals
- User Name: SpAdmin

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #4747

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [x] Add relevant issue to release milestone

### Testing instructions

- Go to record formatters (through app resources or schema config)
- Click on a table
- Click on a formatter
- Add a field
- Do not map it
- Close the record formatter editor overlay 
- You are back to the table list 
- Click save 
- Reopen you record formatter 

- [ ] verify that the unmapped fields have been deleted

### CODE REVIEW

File: specifyweb/frontend/js_src/lib/components/Formatters/Definitions.tsx [hunk 1]
```diff
@@ -52,6 +54,19 @@ export function Definitions({
       ? [{ value: undefined, fields: [] }]
       : trimmedFields;
 
+  React.useEffect(() => {
+    let isFieldUndefined = false;
+
+    formatter.definition.fields.map((item) =>
```
Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/components/Formatters/Definitions.tsx:60]: use .some() instead of .map()

**Review by maxpatiiuk — CHANGES_REQUESTED** [review]
this adds a lot of complexity - why not just filter out unmapped fields before saving (either in react, or in the spec - I can help with that if you need)

**Review by emenslin — CHANGES_REQUESTED** [review]
### Testing instructions

- Go to record formatters (through app resources or schema config)
- Click on a table
- Click on a formatter
- Add a field
- Do not map it
- Close the record formatter editor overlay 
- You are back to the table list 
- Click save 
- Reopen you record formatter 

- [x] verify that the unmapped fields have been deleted 

Unmapped fields get removed after saving! 
However if you add another table as a field (e.g. division) and don't map it when you save and open it again it maps to 'formatted' instead of getting removed like the others. 

https://github.com/specify/specify7/assets/150940840/6784a2be-e774-4ba8-b135-d591570e84ac

**Comment by CarolineDenis** [comment]
@grantfitzsimmons, 
What do we think of this? 

> Unmapped fields get removed after saving!
> However if you add another table as a field (e.g. division) and don't map it when you save and open it again it maps to 'formatted' instead of getting removed like the others.

**Review by combs-a — CHANGES_REQUESTED** [review]
- [ ] verify that the unmapped fields have been deleted 

Looks good! Unmapped fields are also filtered in conditional format.

However, you can add as many blank/invalid definitions as you want to conditional format and save it, which causes infinite load and error messages. (Example of 'invalid definition' would be putting something besides true/false in a true/false field).

Saving the formatter:

https://github.com/specify/specify7/assets/71564869/4db3d167-d1e5-450b-bc58-c48e78bccf43

Querying w/ an invalid formatter:

https://github.com/specify/specify7/assets/71564869/d17280fb-d38f-4f19-91af-9c8f6734cf6f

Crash report:
[Specify 7 Crash Report - 2024-04-10T14 10 35.870Z.txt](https://github.com/specify/specify7/files/14933438/Specify.7.Crash.Report.-.2024-04-10T14.10.35.870Z.txt)

This was all in Firefox w/ Windows 10, on the Herps-PC collection in sdnhm_herps.

**Comment by CarolineDenis** [comment]
> Querying w/ an invalid formatter:
This is an issue but not related to this PR

**Review by combs-a — APPROVED** [review]

**Review by maxpatiiuk — APPROVED** [review]
