### PR TITLE
Always show saveBlocker dialog for unclaimed blockers

### LINKED ISSUE #4693: Choosing a picklist item prevents form from being saved
**Describe the bug** 
After selecting a pick list item in this instance, the form can not be saved. This is not something I can recreate every time, but after one or two refreshes it happens. This pick list in particular is affected, and cannot recreate in `v7`.

**To Reproduce**

1. Go to https://fitznhmaoct2023-edge.test.specifysystems.org/specify/view/collectionobject/608836/
2. Add a new "Col Obj Attribute" record
3. Choose an item from the "Sex" pick list
4. See that the Save button is blocked

**Expected behavior**
It should allow you to save after selecting a value from the pick list. It should also indicate _why_ it is blocking the save.

**Screenshots**

https://github.com/specify/specify7/assets/37256050/f323d3c0-97d0-4dd7-8912-aa314f992b20

[Specify 7 System Information - 2024-03-27T18_27_51.565Z.txt](https://github.com/specify/specify7/files/14779952/Specify.7.System.Information.-.2024-03-27T18_27_51.565Z.txt)

### LINKED ISSUE #4705: Can't add a new locality record from saved collecting event record.
**Describe the bug**
Once a collecting event record has been saved, user cannot add a new locality record.

**To Reproduce**
1. Open new collecting event record.
2. Save collecting event record.
3. Click plus button to create a new locality record.
4. Save locality record.

Save button on the collecting event form turns red, sometimes takes a few seconds and then turns red. Does not happen if you add the new locality before the collecting event record is saved.

Did not happen in 7.9.3. Tested in fwri and KU Paleobotany

**Expected behavior**
To be able to save a collecting event after adding a new locality.

**Screenshots**

Uploading Screen Recording 2024-03-29 at 4.59.59 PM.mov…

### PR DESCRIPTION
**Pull request by melton-jason**
Fixes #4693 
Fixes #4705 

The issue from https://github.com/specify/specify7/issues/4693#issue-2211660635 was that adding a `Col Obj Attribute` to an existing CollectionObject saved triggered a `resource.change` for every field on the CollectionObject.
This caused business rules to be triggered for every field. 
There is a uniqueness rule for CollectionObject which states that `uniqueIdentifier` must be unique at a database level. 
Thus the uniqueness rule was triggered (as there are other CollectionObjects with NULL uniqueIdentifer) and the saveBlocker was set. Since the field was not present on the CollectionObject form, no indication was made to the user.

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add automated tests
- [x] Add relevant issue to release milestone

### Testing instructions
1. Make sure a CollectionObject from has the `collectionObjectAttribute` relationship as a subview and does not have the `uniqueIdentifier` field
2. Find an existing CollectionObject which does not have a `Col Obj Attribute`
3.  Add a Col Obj Attribute to the Collection Object and ensure a saveBlocker is not set 
4.  In SchemaConfig, make `uniqueIdentifier` required on CollectionObject
5. Repeat steps 2-3, but this time make sure a saveBlocker is set and a dialog appears saying uniqueIdentifier must be unique to the database 
6. Add uniqueIdentifier to the CollectionObject form (or use the AutoGenerated Form) and ensure the uniqueness rule functions correctly

### CODE REVIEW

**Review by CarolineDenis — APPROVED** [review]

File: specifyweb/frontend/js_src/lib/components/DataModel/businessRules.ts [hunk 1]
```diff
@@ -335,10 +335,18 @@ export class BusinessRuleManager<SCHEMA extends AnySchema> {
...
           } = otherFieldValues;
           const { id, cid, value } = fieldValues[fieldName];
+          const field = this.resource.specifyTable.getField(fieldName);
           if (otherCid !== undefined && cid !== undefined && otherCid === cid)
             return true;
           if (otherId !== undefined && id !== undefined && otherId === id)
             return true;
+          if (
+            field !== undefined &&
+            !(field.isRequired || field.localization.isrequired) &&
```
Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/components/DataModel/businessRules.ts:345]: the `field.localization.isrequired` check is redundant as it's already included in `field.isRequired`

https://github.com/specify/specify7/blob/b331ce9c552e90d86fc4811a7089fab6ac29c07e/specifyweb/frontend/js_src/lib/components/DataModel/specifyField.ts#L134-L139

**Comment by melton-jason** [comment]
@specify/ux-testing 

When testing this, can #4705 be tested as well? You should not be able to recreate the issue on this branch

**Review by grantfitzsimmons — APPROVED** [review]
> ### Testing instructions
> 1. Make sure a CollectionObject from has the `collectionObjectAttribute` relationship as a subview and does not have the `uniqueIdentifier` field
> 2. Find an existing CollectionObject which does not have a `Col Obj Attribute`
> 3.  Add a Col Obj Attribute to the Collection Object and ensure a saveBlocker is not set 

Can confirm that this fixes https://github.com/specify/specify7/issues/4693

> 4.  In SchemaConfig, make `uniqueIdentifier` required on CollectionObject
> 5. Repeat steps 2-3, but this time make sure a saveBlocker is set and a dialog appears saying uniqueIdentifier must be unique to the database 

image

> 6. Add uniqueIdentifier to the CollectionObject form (or use the AutoGenerated Form) and ensure the uniqueness rule functions correctly 

image

Looks good! 👍

File: specifyweb/frontend/js_src/lib/components/DataModel/businessRules.ts (hunk 1 above)
Comment (melton-jason) [reply specifyweb/frontend/js_src/lib/components/DataModel/businessRules.ts:345]: Currently the `field.localization.isrequired` is not present in `field.isRequired`. 
The `fieldDefinition` only contains information from the `specify_datamodel.xml` (https://files.specifysoftware.org/schema/version/2.10/), and does not contain any information on the splocalecontaineritem which represents the disclipline's configuration for the field. 

Consider the two CollectionObject fields `uniqueIdentifier` and `totalValue`. 
In the currently logged in discipline, `totalValue` is marked as required and  `uniqueIdentifier` is not required. 

The following code is added to the constructor of `FieldBase`
```ts
if (
      table.name === 'CollectionObject' &&
      ['totalvalue', 'uniqueidentifier'].includes(
        fieldDefinition.name.toLowerCase()
      )
    )
      console.log(
        table.name,
        fieldDefinition.name,
        table.localization.items[fieldDefinition.name.toLowerCase()]
          ?.isrequired,
        fieldDefinition.required,
        this.isRequired
      );
 ```

which outputs: 

Screenshot 2024-04-01 at 9 22 48 AM

---

I agree it would make sense to include the `field.localization.isrequired` with the `field.isRequired`.

**Review by bronwyncombs — APPROVED** [review]
1. ✅ Make sure a CollectionObject from has the `collectionObjectAttribute` relationship as a subview and does not have the `uniqueIdentifier` field
2. ✅ Find an existing CollectionObject which does not have a `Col Obj Attribute`
3. ✅ Add a Col Obj Attribute to the Collection Object and ensure a saveBlocker is not set 
4. ✅  In SchemaConfig, make `uniqueIdentifier` required on CollectionObject
5. ✅ Repeat steps 2-3, but this time make sure a saveBlocker is set and a dialog appears saying uniqueIdentifier must be unique to the database 
Screenshot 2024-04-01 at 9 49 47 AM


7. ✅ Add uniqueIdentifier to the CollectionObject form (or use the AutoGenerated Form) and ensure the uniqueness rule functions correctly 

Screenshot 2024-04-01 at 9 50 42 AM

In testing for locality with #4705:

Screenshot 2024-04-01 at 9 52 18 AM

Save behaves as expected for locality records added after initial save. 

Looks good!

**Review by lexiclevenger — APPROVED** [review]
### Testing instructions

- [x] Make sure a CollectionObject from has the `collectionObjectAttribute` relationship as a subview and does not have the `uniqueIdentifier` field
- [x] Find an existing CollectionObject which does not have a `Col Obj Attribute`
- [x] Add a Col Obj Attribute to the Collection Object and ensure a saveBlocker is not set 
- [x] In SchemaConfig, make `uniqueIdentifier` required on CollectionObject
- [x] Repeat steps 2-3, but this time make sure a saveBlocker is set and a dialog appears saying uniqueIdentifier must be unique to the database 
- [x] Add uniqueIdentifier to the CollectionObject form (or use the AutoGenerated Form) and ensure the uniqueness rule functions correctly
Screenshot 2024-04-01 at 3 14 00 PM

This also fixed issue #4705.

Initially, the save was blocked, but I left the tab and returned to it after some time and it was no longer blocked. I don't know what I did, and I was not able to recreate this.

File: specifyweb/frontend/js_src/lib/components/DataModel/businessRules.ts (hunk 1 above)
Comment (maxpatiiuk) [reply specifyweb/frontend/js_src/lib/components/DataModel/businessRules.ts:345]: huh, you are correct. then this seems like a bug as the way it stands now, sp7 ignores schema localization completely for the isRequired setting.

could you please fix it? (in this PR or separate)

**Review by maxpatiiuk — CHANGES_REQUESTED** [review]

**Review by maxpatiiuk — APPROVED** [review]
ups, pressed "Request changes" accidentally

File: specifyweb/frontend/js_src/lib/components/DataModel/businessRules.ts (hunk 1 above)
Comment (melton-jason) [reply specifyweb/frontend/js_src/lib/components/DataModel/businessRules.ts:345]: PR #4721
