### PR TITLE
Fetch collection items for picklists

### LINKED ISSUE #6021: Preptype `pick list items` not showing in schema config
**Describe the bug**
In the Preptype picklist in schema config the pick list items don't show up and it just says 'No Data'. Other picklists in production work normally. 

**To Reproduce**

1. Go to schema config 
2. Select preparation -> preptype
3. Click the edit button next to the picklist

**Expected behavior**
The picklist items should appear 

**Screenshots**
Production: 
image

Other picklist in production: 
image

v7.9.6.2: 
image

Please fill out the following information manually:
- OS: Windows 11
- Browser: Chrome
- Specify 7 Version: production
- Database Name: ojsmnh
- Collection name: fossil invertebrates
- User Name: spadmin
- URL: https://ojsmnh110242024production-production.test.specifysystems.org/specify/schema-config/en/Preparation/

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #6021

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good and
      self-explanatory (or properly documented)
- [ ] Add relevant issue to release milestone

### Testing instructions

- Go to schema config
- Select preparation -> preptype
- Click the edit button next to the picklist
- [ ] verify the items are present

### CODE REVIEW

**Review by sharadsw — APPROVED** [review]

**Review by maxpatiiuk — APPROVED** [review]
change looks good, but this component is used in several places so the impact of the change could be larger. could you check all the places where RecordSelectorFromCollection is called without onFetch prop and check if those need to be tested?

**Review by alesan99 — APPROVED** [review]
### Testing instructions

- [x] verify the items are present

---

chrome_EEK8c5mfJv


Looks good 👍

Picklists seem to be good everywhere I checked, but I can re-test if there are other specific areas that might be affected by the pr.

File: specifyweb/frontend/js_src/lib/components/FormSliders/RecordSelectorFromCollection.tsx [hunk 1]
```diff
@@ -82,13 +82,17 @@ export function RecordSelectorFromCollection<SCHEMA extends AnySchema>({
...
       collection.models[index] === undefined
-    )
-      handleFetch();
+    ){
+      if (typeof handleFetch === 'function' ) {
+        handleFetch?.()
+      } else {
+        void collection.fetch() 
+      }
+    }
```
Comment (melton-jason) [inline specifyweb/frontend/js_src/lib/components/FormSliders/RecordSelectorFromCollection.tsx:95]: > change looks good, but this component is used in several places so the impact of the change could be larger. could you check all the places where RecordSelectorFromCollection is called without onFetch prop and check if those need to be tested?

https://github.com/specify/specify7/pull/6032#pullrequestreview-2528496994

Currently, the only place where `RecordSelectorFromCollection` is called/rendered is eventually in [SubView.tsx](https://github.com/specify/specify7/blob/production/specifyweb/frontend/js_src/lib/components/Forms/SubView.tsx) and [PickListEditor.tsx](https://github.com/specify/specify7/blob/production/specifyweb/frontend/js_src/lib/components/FormCells/PickListEditor.tsx), and specifically only the PicklistEditor had the `onFetch` function omitted and `handleFetch` in Subview is never undefined. 

What this means is that as of writing this, the only place this PR affects is when viewing a PickList of type `Entire Table` or type `Field from Table` (through either the normal Data Entry form or through the Schema Config). 

I did test PickLists which had over 20 items (the default fetch limit in Specify), navigating to the 21st record (which fetched the next 20 records), and ensured the ordering of the fetched records were preserved. 

If this causes problems in the future, we can instead make `onFetch` required (as well as in [IntegratedRecordSelector.tsx](https://github.com/specify/specify7/blob/production/specifyweb/frontend/js_src/lib/components/FormSliders/IntegratedRecordSelector.tsx) and always let the 'Parent' component decide what the fetch behavior should be. 
There are definitely cases where the default fetch _shouldn't_ be used[^1], and making the prop required would hopefully encourage thinking about the exact fetch behavior the Parent needs (even if in most cases it will be the default fetch). 

[^1]: [Subview.tsx](https://github.com/specify/specify7/blob/cc04db4e0229c9709e558525dd9bbaa75d2f06b0/specifyweb/frontend/js_src/lib/components/Forms/SubView.tsx#L93-L96), [resourceApi.ts](https://github.com/specify/specify7/blob/cc04db4e0229c9709e558525dd9bbaa75d2f06b0/specifyweb/frontend/js_src/lib/components/DataModel/resourceApi.ts#L643-L647)
