### PR TITLE
Display only record set for current collection

### LINKED ISSUE #4520: Record sets appear in the wrong collection
**Describe the bug**
Record sets that should not appear are showing in the wrong collection

It shows:
`You do not have access to any Collection containing this resource through the currently logged in account`

**To Reproduce**

1. Log in as `petrifiedroadkill` and select "NHMA Vertebrate"
1. Go to https://fitznhmaoct2023-edge.test.specifysystems.org/specify/record-set/344/
2. See that there are record sets visible
3. Go to https://fitznhmaoct2023-v793.test.specifysystems.org/specify/overlay/record-sets/
4. See that there are no record sets visible

Here's an example of one of the record sets visible in `edge` but not in `v7.9.3.1`:

|RecordSetID|TimestampCreated|TimestampModified|Version|CollectionMemberID|AllPermissionLevel|TableID|GroupPermissionLevel|Name|OwnerPermissionLevel|Remarks|Type|SpPrincipalID|CreatedByAgentID|ModifiedByAgentID|SpecifyUserID|InfoRequestID|
|-----------|----------------|-----------------|-------|------------------|------------------|-------|--------------------|----|--------------------|-------|----|-------------|----------------|-----------------|-------------|-------------|
|344|2020-01-16 14:40:08.000|2020-01-16 14:40:08.000|0|32769||1||Aarhus-Ento_1_2020-1-16_14:28|||0||1|1|1||

See that the `CollectionMemberID` references the "NHMA Entomology" collection, which this user does not have access to anymore:

|collectionId|CollectionName|
|------------|--------------|
|32769|NHMA Entomology|

This indicates record sets are not being filtered by collection properly.

**Screen Recording:**

https://github.com/specify/specify7/assets/37256050/1a5e3ccc-e8c6-478b-9ebd-a4f7fdf91d73

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #4520

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [x] Add relevant issue to release milestone

### Testing instructions

go to record sets dialog overlay
verify that all record sets proposed are part of the collection you are connected in

### CODE REVIEW

**Review by maxpatiiuk — APPROVED** [review]
nice!
could you add a TODO inside of fetchCollection saying that `domainFilter` does not filter for tables that are scoped using the collectionMemberId field rather than a relationship?

**Review by emenslin — APPROVED** [review]
Looks good, record sets are now scoped to the right collection.

**Review by grantfitzsimmons — APPROVED** [review]

File: specifyweb/frontend/js_src/lib/components/Toolbar/RecordSets.tsx [hunk 1]
```diff
@@ -79,6 +80,8 @@ export function RecordSetsDialog({
 
   const [data] = useAsyncState(
     React.useCallback(
+      /** domainFilter does filter for tables that are
```
Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/components/Toolbar/RecordSets.tsx:83]: did you mean to say "does **not** filter"?

Comment (melton-jason) [reply specifyweb/frontend/js_src/lib/components/Toolbar/RecordSets.tsx:83]: This comment is technically correct, assuming it means the backend does correctly scope tables which only have the `collectionmemberid` field:

https://github.com/specify/specify7/blob/c98c9c3341fc72a9610ee65e7689180a8e6a31e0/specifyweb/specify/filter_by_col.py#L36-L39

Though we have to manually specify the `collectionmemberid` here because the frontend currently does not handle the case where a table is only scoped by the `collectionmemberid` field (see https://github.com/specify/specify7/pull/4542#pullrequestreview-1894657939 and a list of tables which also exhibit this bug in https://github.com/specify/specify7/pull/4542#issuecomment-1959756209)

The comment can likely be expanded to include a little more context, if needed
