### PR TITLE
fix(FormEditor): make CollectionRelPlugin not throw on outside form

### LINKED ISSUE #4789: bug: Collection relationship plugin throws error when opened in form editor
Error:
> Related collection plugin used with relation that doesn't match current collection

Happens when you opened a Collection Object form belonging to a different collection.

The error should be suppressed when the form is opened though a form editor

Screenshot 2024-04-13 at 07 31 56

[Specify 7 Crash Report - 2024-04-13T14_32_07.207Z.txt.zip](https://github.com/specify/specify7/files/14967647/Specify.7.Crash.Report.-.2024-04-13T14_32_07.207Z.txt.zip)

### PR DESCRIPTION
**Pull request by maxpatiiuk**
Fixes #4789

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [x] Add relevant issue to release milestone

### Testing instructions

1. In form editor, open a Collection Object form that does not belong to the collection you are in right now, and that has a collection relationship plugin
2. No exception toast message should be shown in the top right corner of the screen

### CODE REVIEW

**Review by pashiav — APPROVED** [review]
### Testing instructions

- [X] 1. In form editor, open a Collection Object form that does not belong to the collection you are in right now, and that has a collection relationship plugin
- [X] 2. No exception toast message should be shown in the top right corner of the screen

---
Looks good! No errors appearing.
Screen Shot 2024-04-15 at 9 58 00 AM

File: specifyweb/frontend/js_src/lib/components/FormPlugins/collectionRelData.ts [hunk 1]
```diff
@@ -59,7 +59,8 @@ export const processColRelationships = async (
 export async function fetchOtherCollectionData(
   resource: SpecifyResource<CollectionObject>,
   relationship: string,
-  formatting: string | undefined
+  formatting: string | undefined,
+  isInFormEditor: boolean
```
Comment (melton-jason) [inline specifyweb/frontend/js_src/lib/components/FormPlugins/collectionRelData.ts:63]: (optional)

Not the biggest fan of calling the parameter `isInFormEditor`. 
Is there a possibility this function will be used outside of rendering the CollectionRelPlugin? 

The name is descriptive for the current uses/callers of `fetchOtherCollectionData` for _why_ the parameter is needed but does not provide information regarding what the parameter does. 

Specifically, callers of the function will likely need to inspect the body of the function to determine what `isInFormEditor` does and how it alters the function's behavior (especially since it is required). 

If it is likely this will be used outside of rendering the plugin, maybe something like `muteIncorrectCollectionError`?

**Review by melton-jason — APPROVED** [review]

File: specifyweb/frontend/js_src/lib/components/FormPlugins/collectionRelData.ts (hunk 1 above)
Comment (maxpatiiuk) [reply specifyweb/frontend/js_src/lib/components/FormPlugins/collectionRelData.ts]: good point - improved

**Review by bronwyncombs — APPROVED** [review]
- [X] 1. In form editor, open a Collection Object form that does not belong to the collection you are in right now, and that has a collection relationship plugin
- [X] 2. No exception toast message should be shown in the top right corner of the screen

Screenshot 2024-04-16 at 10 24 48 AM

**Review by melton-jason — APPROVED** [review]
😃
