### PR TITLE
Fix Query Builder using Tree rank names instead of titles

### LINKED ISSUE #1050: Query does not show tree rank titles
Barcelona observed that the query was showing the rank name instead of the title, which they had changed to their own language.
this is what the query looks like:
image
This is what the titles look like in their definitions:
image

### PR DESCRIPTION
**Pull request by maxxxxxdlp**
Closes #1050

### CODE REVIEW

**Review by grantfitzsimmons — DISMISSED** [review]
On the picklist, the tree rank shows the title. After that is selected, the query shows the name of the rank.

**Comment by maxxxxxdlp** [comment]
@benanhalt the issue @grantfitzsimmons found occurs at this line: 
https://github.com/specify/specify7/blob/233b8931faf3d12bcccc45f4bc35db294706af2f/specifyweb/frontend/js_src/lib/queryfield.js#L161

Field name get's printed, rather than the field title

I am not sure where should I get treeDefItems from in this scope. Do you store that information anywhere or should I fetch it here?

**Comment by benanhalt** [comment]
@maxxxxxdlp I think you will just have to fetch them for now. Some day the tree definitions should be set up to just load at start up. But that is a broader scope fix than this issue.

Also, the tree level names are used in the header for the results, so that probably needs to be changed to use the titles as well.

**Review by benanhalt — COMMENTED** [review]
See the comment about fetching tree levels.

**Comment by maxxxxxdlp** [comment]
Fixed in 6595f9c2
The code is looking ugly with all that in-place rank fetching.
Would need to do a comprehensive refactor at some point.

File: specifyweb/frontend/js_src/lib/queryfield.js [hunk 1]
```diff
@@ -11,6 +11,10 @@ var QueryFieldSpec    = require('./queryfieldspec.js');
 var QueryFieldInputUI = require('./queryfieldinput.js');
 const queryText = require('./localization/query').default;
 const commonText = require('./localization/common').default;
+const dataModelStorage = require('./wbplanviewmodel').default;
```
Comment (benanhalt) [inline specifyweb/frontend/js_src/lib/queryfield.js:14]: I'd rather you not use Workbench code here. 

Use code similar to https://github.com/specify/specify7/blob/e369d1f81a4234d74998ca5c852f37c66d4869e0/specifyweb/frontend/js_src/lib/queryfield.js#L232-L245

File: specifyweb/frontend/js_src/lib/queryresultstable.js [hunk 2]
```diff
@@ -10,11 +10,29 @@ var ScrollResults = require('./scrollresults.js');
 var QueryResults  = require('./queryresults.js');
 const queryText = require('./localization/query').default;
 const commonText = require('./localization/common').default;
+const dataModelStorage = require('./wbplanviewmodel').default;
```
Comment (benanhalt) [inline specifyweb/frontend/js_src/lib/queryresultstable.js:13]: Also here. Use `domian.getTreeDef` instead. That way when that gets refactored, this will get fixed.

**Review by benanhalt — CHANGES_REQUESTED** [review]

File: specifyweb/frontend/js_src/lib/queryfield.js (hunk 1 above)
Comment (maxxxxxdlp) [reply specifyweb/frontend/js_src/lib/queryfield.js:14]: > Some day the tree definitions should be set up to just load at start up. But that is a broader scope fix than this issue.

dataModelStorage serves exactly that purpose. It stores the names and titles of all tree ranks

> I'd rather you not use Workbench code here.

wbplanviewmodel does not depend on other workbench files. It might be appropriate to rename it. Also, it is already used outside of the workbench (Leaflet and S^N)

And unlike schema.models, dataModelStorage has type definitions

Do you still want me to revert to fetching tree definitions here?

Comment (benanhalt) [reply specifyweb/frontend/js_src/lib/queryfield.js:14]: Yes, please. The whole data model is not needed in this context, just the tree definition.

**Review by benanhalt — APPROVED** [review]
