### PR TITLE
Do not define busRules if not present in 6

### LINKED ISSUE #4815: Specify 7 adds invalid business rule references to new form definitions
**Describe the bug**
`edge` introduces a bug when using the visual editor to create a form definition for the "ExsiccataItem" table. The generated XML includes a reference to non-existent business rules (`edu.ku.brc.specify.datamodel.busrules.ExsiccataItemBusRules`), causing Specify 6 to crash when trying to open the form.

*Impact:* Users who create forms with the Specify 7 visual editor and then try to open those forms in Specify 6 will encounter a crash.

*Cause:* The visual editor in Specify 7 incorrectly adds a `busrules` attribute to the `<view>` element in the generated XML for the "ExsiccataItem" form definition. This attribute references a Java class that doesn't exist, leading to the crash in Specify 6.

*Workaround:*
1. *Use manual editing:* Manually create the form definition for "ExsiccataItem" in Specify 7 using the XML editor. This avoids the bug introduced by the visual editor.

---

While it appears that the `busrules` reference was assumed to be safe for most popular tables, many tables in the model that can have form definitions lack a dedicated `{TableName}BusRules.java` file and do not have associated rules.

https://github.com/specify/specify6/tree/master/src/edu/ku/brc/specify/datamodel/busrules

After searching the entirety of the `config` directory in Specify 6, no references to `edu.ku.brc.specify.datamodel.busrules.ExsiccataItemBusRules` were found.

image

@melton-jason Can you confirm this to be the underlying issue?

This issue does not cause problems in Specify 7 but prevents Specify 6 from opening forms with these invalid rules.

**To Reproduce**

You'll need to have this database accessible in both Specify 6 and 7, or you'll need to make a backup of the database after performing the XML editing steps in 7 for use in Specify 6.

**Specify 7:**
1. Go to any form definition
2. Use the visual editor
3. Check the "Show All Tables" button
4. Go to `Exsiccata Item` in the table list
5. Create a new form based on the `Botany > Manager > Botany` `ExsiccataItem` definition
   image
6. Create and save it. Remember the name assigned to this view definition.
7. Save the form definition.
8. Go to the view definition currently being used for Collection Object.
9. Add this row to the Collection Object form, replacing the `viewname` with the name of the view definition created above if it was changed from the default.
   ```xml
   <row>
      <cell type="subview" id="8" name="exsiccataItems" viewname="ExsiccataItem" defaulttype="table" colspan="13"/>
   </row>
    ```
7. Save the form definition.
8. Verify the forms appear and work well in Specify 7 (they should!) 😊 

image

**Specify 6:**
10. Launch Specify 6 using this same form definition logged in as the same user.
11. Try to open the Collection Object form
12. See that it does not open and rather does nothing.

image

In the [Specify log](https://discourse.specifysoftware.org/t/how-to-send-an-error-or-specify-log-file/771), you should see this:
```
************************ Type: App  Action: StartUp
10:06:50 DEBUG specify.config.SpecifyAppContextMgr:2439 - getResourceAsXML: null
10:06:50 DEBUG specify.config.SpecifyAppContextMgr:2439 - getResourceAsXML: null
10:06:50  INFO brc.specify.Specify:2376 - positionAndFitToScreen(javax.swing.JFrame[frame0,244,93,1024x796,hidden,layout=java.awt.BorderLayout,title=Specify 6.8.03,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,28,1024x768,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true], 703, -1078, 1280, 944)
10:06:52  WARN brc.ui.UIRegistry:533 - Couldn't find key[Save] in resource bundle [resources]
The field 'mod' (modifier) is hidden in the schema and shouldn't be used on the Form 'Collection Object'.
The field '9' (confidence) is hidden in the schema and shouldn't be used on the Form 'Determination'.
The field '8' (qualifier) is hidden in the schema and shouldn't be used on the Form 'Determination'.
The field 'an' (alternateName) is hidden in the schema and shouldn't be used on the Form 'Determination'.
The field '9' (confidence) is hidden in the schema and shouldn't be used on the Form 'Determination Table'.
The field '8' (qualifier) is hidden in the schema and shouldn't be used on the Form 'Determination Table'.
The field 'an' (alternateName) is hidden in the schema and shouldn't be used on the Form 'Determination Table'.
The field '2' (text2) is hidden in the schema and shouldn't be used on the Form 'Collection Object'.
Exception in thread "AWT-EventQueue-0" java.lang.InternalError: Can't instantiate BusinessRulesIFace [edu.ku.brc.specify.datamodel.busrules.ExsiccataItemBusRules]
	at edu.ku.brc.af.ui.forms.persist.View.createBusinessRule(View.java:298)
	at edu.ku.brc.af.ui.forms.FormViewObj.<init>(FormViewObj.java:341)
	at edu.ku.brc.af.ui.forms.ViewFactory.buildFormViewable(ViewFactory.java:2588)
	at edu.ku.brc.af.ui.forms.ViewFactory.buildViewable(ViewFactory.java:253)
	at edu.ku.brc.af.ui.forms.ViewFactory.createFormView(ViewFactory.java:2881)
	at edu.ku.brc.af.ui.forms.MultiView.createViewable(MultiView.java:979)
	at edu.ku.brc.af.ui.forms.MultiView.createViewable(MultiView.java:935)
	at edu.ku.brc.af.ui.forms.MultiView.<init>(MultiView.java:258)
	at edu.ku.brc.af.ui.forms.ViewFactory.createItem(ViewFactory.java:1995)
	at edu.ku.brc.af.ui.forms.ViewFactory.processRows(ViewFactory.java:2194)
	at edu.ku.brc.af.ui.forms.ViewFactory.buildFormViewable(ViewFactory.java:2602)
	at edu.ku.brc.af.ui.forms.ViewFactory.buildViewable(ViewFactory.java:253)
	at edu.ku.brc.af.ui.forms.ViewFactory.createFormView(ViewFactory.java:2881)
	at edu.ku.brc.af.ui.forms.MultiView.createViewable(MultiView.java:979)
	at edu.ku.brc.af.ui.forms.MultiView.createViewable(MultiView.java:935)
	at edu.ku.brc.af.ui.forms.MultiView.<init>(MultiView.java:280)
	at edu.ku.brc.af.ui.forms.MultiView.<init>(MultiView.java:146)
	at edu.ku.brc.af.tasks.subpane.FormPane.createForm(FormPane.java:426)
	at edu.ku.brc.af.tasks.subpane.FormPane.<init>(FormPane.java:196)
	at edu.ku.brc.specify.tasks.DataEntryTask.openView(DataEntryTask.java:292)
	at edu.ku.brc.specify.tasks.DataEntryTask.processDataEntryCommands(DataEntryTask.java:1836)
	at edu.ku.brc.specify.tasks.DataEntryTask.doCommand(DataEntryTask.java:2367)
	at edu.ku.brc.ui.CommandDispatcher.dispatch(CommandDispatcher.java:122)
	at edu.ku.brc.af.core.NavBoxAction.actionPerformed(NavBoxAction.java:179)
	at edu.ku.brc.ui.RolloverCommand.doAction(RolloverCommand.java:765)
	at edu.ku.brc.ui.RolloverCommand$1.mouseReleased(RolloverCommand.java:212)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: edu.ku.brc.specify.datamodel.busrules.ExsiccataItemBusRules
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at edu.ku.brc.af.ui.forms.persist.View.createBusinessRule(View.java:291)
	... 57 more
```

The underlying issue is that Specify 6 does not recognize `ExsiccataItemBusRules`, and Specify 7 is adding a reference to these non-existent business rules in the form definition.

## Explanation
I confirmed that manually adding the `ExsiccataItem` `<view>` and `<viewdef>` did not result in this issue, but using the visual editor made it inaccessible in Specify 6. When extracting both sections (the manual and automatically created ones), I saw this:

**Added manually in XML editor in Specify 7:**
```xml
        <view name="ExsiccataItem"
            class="edu.ku.brc.specify.datamodel.ExsiccataItem"
            resourcelabels="false">
            <desc><![CDATA[Project form.]]></desc>
            <altviews>
                <altview name="ExsiccataItem View" viewdef="ExsiccataItem" mode="view"/>
                <altview name="ExsiccataItem Edit" viewdef="ExsiccataItem" mode="edit" default="true"/>
            </altviews>
        </view>
		<viewdef name="ExsiccataItem" class="edu.ku.brc.specify.datamodel.ExsiccataItem" type="form" gettable="edu.ku.brc.af.ui.forms.DataGetterForObj" settable="edu.ku.brc.af.ui.forms.DataSetterForObj">
			<desc>Form for ExsiccataItem</desc>
			<!--columnDef>p,2px,p,2px,100px,2px,p,2px,100px,2px,100px,p:g</columnDef-->
			<columnDef>p,2px,100px,2px,p,2px,100px,2px,p,p:g</columnDef>
			<rowDef auto="true" sep="2px" cell="p"/>
			<rows>
				<row>
					<cell type="label" labelfor="exsiccata"/>
					<cell type="field" id="exsiccata" name="exsiccata" uitype="querycbx" initialize="name=Exsiccata" colspan="5"/>
				</row>
				<row>
					<cell type="label" labelfor="1"/>
					<cell type="field" id="1" name="fascicle" uitype="text"/>
					<cell type="label" labelfor="2"/>
					<cell type="field" id="2" name="number" uitype="text"/>
				</row>
			</rows>
		</viewdef>
```

**WORKING manually defined definition:** [ManualExsiccataItem.xml.zip](https://github.com/specify/specify7/files/15065155/ManualExsiccataItem.xml.zip)

**Created by the Visual Editor in Specify 7:**
```xml
		<view name="ExsiccataItem" class="edu.ku.brc.specify.datamodel.ExsiccataItem" resourcelabels="false" busrules="edu.ku.brc.specify.datamodel.busrules.ExsiccataItemBusRules">
			<desc>Project form.</desc>
			<altviews>
				<altview name="ExsiccataItem View" viewdef="ExsiccataItem" mode="view"/>
				<altview name="ExsiccataItem Edit" viewdef="ExsiccataItem" mode="edit" default="true"/>
			</altviews>
		</view>
		<viewdef name="ExsiccataItem" class="edu.ku.brc.specify.datamodel.ExsiccataItem" type="form" gettable="edu.ku.brc.af.ui.forms.DataGetterForObj" settable="edu.ku.brc.af.ui.forms.DataSetterForObj">
			<desc>Form for ExsiccataItem</desc>
			<!--columnDef>p,2px,p,2px,100px,2px,p,2px,100px,2px,100px,p:g</columnDef-->
			<columnDef>p,2px,100px,2px,p,2px,100px,2px,p,p:g</columnDef>
			<rowDef auto="true" sep="2px" cell="p"/>
			<rows>
				<row>
					<cell type="label" labelfor="exsiccata"/>
					<cell type="field" id="exsiccata" name="exsiccata" uitype="querycbx" initialize="name=Exsiccata" colspan="5"/>
				</row>
				<row>
					<cell type="label" labelfor="1"/>
					<cell type="field" id="1" name="fascicle" uitype="text"/>
					<cell type="label" labelfor="2"/>
					<cell type="field" id="2" name="number" uitype="text"/>
				</row>
			</rows>
		</viewdef>
```

**BUGGED Visual editor defined definition:** [BUGVisualExsiccataItem.xml.zip](https://github.com/specify/specify7/files/15065161/BUGVisualExsiccataItem.xml.zip)

Nothing of note is different between these two aside from one **very** important thing. In the `<view>` section, you can see a reference to a set of business rules:

```
<view name="ExsiccataItem" class="edu.ku.brc.specify.datamodel.ExsiccataItem" resourcelabels="false" busrules="edu.ku.brc.specify.datamodel.busrules.ExsiccataItemBusRules">
```

Presumably, Specify 6 reads this and fails to instantiate `BusinessRulesIFace` as this rule doesn't exist as a `java` file in the `src/edu/ku/brc/specify/datamodel/busrules` directory.

https://github.com/specify/specify6/tree/master/src/edu/ku/brc/specify/datamodel/busrules

**Crash Report**
[Specify 7 System Information - 2024-04-22T15_26_39.984Z.txt](https://github.com/specify/specify7/files/15065168/Specify.7.System.Information.-.2024-04-22T15_26_39.984Z.txt)

Please, also fill out the following information manually:

- OS: macOS
- Browser: Arc
- Specify 7 Version: `edge`
- Database Name: `ku_vascplant` (local)
- Collection name: KU Vascular Plant
- User Name: spadmin

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #4815

### Checklist

- [x] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [x] Add relevant issue to release milestone

### Testing instructions

- On any ViewSet, add or copy (from the defaults) a new view definition for any of the following tables (non-exhaustive list): AddressOfRecord, ExsiccataItem, MaterialSample, BorrowMaterial
- In the Visual Editor, make any (valid) change on the view definition and save the ViewSet
- [ ] In the `XML Editor` view, ensure that the `view` element for the `viewdef` does not contain a `busrule` attribute

---

- On any ViewSet, add or copy (from the defaults) a new view definition for the `Shipment` table
- In the Visual Editor, make any (valid) change on the view definition and save the ViewSet
- [ ] In the `XML Editor` view, ensure that the `view` element for the created Shipment view contains `busrule="edu.ku.brc.specify.datamodel.busrules.LoanGiftShipmentBusRules"`

---

- Create a new ViewSet as a copy of `BackStop > Global`
- In the `Visual Editor`, make any change (such as adding/copying a new view definition, modifying an existing view definition) and save the ViewSet
- [ ] In the `XML Editor` view, search for `Biostrat` and ensure the Biostrat `view` has `busrule="edu.ku.brc.specify.datamodel.busrules.BioStratBusRules"` 

- [ ] Open any of the modified views in Specify 6 and ensure they are displayed correctly

### CODE REVIEW

**Comment by CarolineDenis** [comment]
NOTES: 
- improve conditional

**Review by grantfitzsimmons — APPROVED** [review]
Works as expected! When defining a `Determination` form definition, the `busrules` are set appropriately. When defining an `ExsiccataItem` form definition, no `busrules` are set in the `<view>`. 

image

Views configured in 7 appear as they should in 6, both from scratch and when using a template.

File: specifyweb/frontend/js_src/lib/components/FormEditor/spec.ts [hunk 1]
```diff
@@ -48,6 +48,127 @@ export type ViewSets = Omit<RawViewSets, 'viewDefs'> & {
   >;
 };
 
+const tablesWithNoBusRulesIn6 = new Set([
```
Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/components/FormEditor/spec.ts:51]: this list is rather long - probably longer than the inverse list
and also, it's unlikely that more business rules will be added in sp6, but it's highly likely that more tables will be added in sp7
thus, you should invert this list and define the tables with business rules

**Review by maxpatiiuk — CHANGES_REQUESTED** [review]

File: specifyweb/frontend/js_src/lib/components/FormEditor/__tests__/__snapshots__/index.test.ts.snap [hunk 2]
```diff
@@ -45,7 +45,7 @@ exports[`Can edit a form definition 2`] = `
 "<?xml version=\\"1.0\\" encoding=\\"UTF-8\\"?>
 <viewset name=\\"Fish Views\\" xmlns:xsi=\\"http://www.w3.org/2001/XMLSchema-instance\\">
 	<views>
-		<view name=\\"Accession\\" class=\\"edu.ku.brc.specify.datamodel.Accession\\" busrules=\\"edu.ku.brc.specify.datamodel.busrules.AccessionBusRules\\" resourcelabels=\\"false\\">
+		<view name=\\"Accession\\" class=\\"edu.ku.brc.specify.datamodel.Accession\\" busrules=\\"edu.ku.brc.specify.datamodel.busrules.\\" resourcelabels=\\"false\\">
```
Comment (grantfitzsimmons) [inline specifyweb/frontend/js_src/lib/components/FormEditor/__tests__/__snapshots__/index.test.ts.snap:48]: This is incorrect

File: specifyweb/frontend/js_src/lib/components/FormEditor/spec.ts [hunk 3]
```diff
@@ -48,125 +48,86 @@ export type ViewSets = Omit<RawViewSets, 'viewDefs'> & {
...
-  'VoucherRelationship',
-  'Workbench',
-  'WorkbenchDataItem',
-  'WorkbenchRow',
-  'WorkbenchRowExportedRelationship',
-  'WorkbenchRowImage',
-  'WorkbenchTemplate',
-  'WorkbenchTemplateMappingItem',
+const tablesWithBusRulesIn6 = new Set([
+  'AccessionAgentBusRules',
```
Comment (grantfitzsimmons) [inline specifyweb/frontend/js_src/lib/components/FormEditor/spec.ts:52]: Each of these has `BusRules` at the end, where it previously did not. I expect it to behave incorrectly after this change, but I can review once it has been adjusted or my fears have been alleviated! 😄

**Review by grantfitzsimmons — DISMISSED** [review]

File: specifyweb/frontend/js_src/lib/components/FormEditor/__tests__/__snapshots__/index.test.ts.snap (hunk 2 above)
Comment (grantfitzsimmons) [reply specifyweb/frontend/js_src/lib/components/FormEditor/__tests__/__snapshots__/index.test.ts.snap:48]: From `common.views.xml`:
```xml
        <view name="Accession"
              class="edu.ku.brc.specify.datamodel.Accession"
              busrules="edu.ku.brc.specify.datamodel.busrules.AccessionBusRules"
        >
            <desc><![CDATA[The Accession form.]]></desc>
            <altviews>
                <altview name="Accession View" viewdef="Accession" mode="view" default="true"/>
                <altview name="Accession Edit" viewdef="Accession" mode="edit"/>
            </altviews>
        </view>
```

Comment (grantfitzsimmons) [reply specifyweb/frontend/js_src/lib/components/FormEditor/__tests__/__snapshots__/index.test.ts.snap]: Fixed in https://github.com/specify/specify7/pull/4816/commits/46a98f081894f0cb2c4b66834bcdc0e652d3176d

**Review by combs-a — COMMENTED** [review]
Currently, when I create a new ExsiccataItem with New in App Resources at the user level, checking it in the editor still says that it has busrules:

https://sdnhmherps2824-issue-4815.test.specifysystems.org/specify/resources/view-set/5/
image

Same with Common Name (which doesn't seem to be in the set with busrules, though I may have missed it):
image

I'm not sure if the busrules should be in the format seen above or if it's supposed to be entirely removed, so please let me know if that's expected.

Set does seem to be working; used Disposal Agent and it added the correct stuff, looks good!
image

This is just a check using Specify 7 since I'm having a few issues with editing between 6 and 7, but I'll try and check this with 6 when I finish troubleshooting the issues I'm having currently.

File: specifyweb/frontend/js_src/lib/components/FormEditor/spec.ts [hunk 4]
```diff
@@ -64,8 +146,11 @@ const resolvedViewSpec = () =>
         businessRules: localized(
           typeof table === 'object'
             ? `edu.ku.brc.specify.datamodel.busrules.${
-                businessRules[table.name] ?? table.name
-              }BusRules`
+                businessRules[table.name] ||
```
Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/components/FormEditor/spec.ts:149]: @combs-a is correct in https://github.com/specify/specify7/pull/4816#pullrequestreview-2018353684
if current table does not have business rules, you should return undefined here, rather than a broken string

**Review by melton-jason — COMMENTED** [review]
Another solution for Specify6 which may be cleaner is to remove the `busRules` attribute for `views` elements and instead replace it with `usedefbusrule="true"`. 

This will use the `class` attribute of the view to resolve the table and return and use the Class defined at the `businessrule` attribute from the  table's entry in the `specify_datamodel.xml`. 
In this case, if the table does not have a businessrule class defined, Specify 6 uses a base BusinessRule class instead of throwing an error. 

See below for the Specify 6 code

---

https://github.com/specify/specify6/blob/945d28f00288d2d64979848fb2fb63fda34bdd1b/src/edu/ku/brc/af/ui/forms/persist/View.java#L287-L308

```java
        if (StringUtils.isNotEmpty(businessRulesClassName))
        {
            try 
            {
                businessRule =  (BusinessRulesIFace)Class.forName(businessRulesClassName).newInstance();
                 
            } catch (Exception e) 
            {
                edu.ku.brc.af.core.UsageTracker.incrHandledUsageCount();
                edu.ku.brc.exceptions.ExceptionTracker.getInstance().capture(View.class, e);
                
                InternalError error = new InternalError("Can't instantiate BusinessRulesIFace [" + businessRulesClassName + "]");
                error.initCause(e);
                throw error;
            }
            
        } else if (useDefaultBusRules)
        {
            businessRule = DBTableIdMgr.getInstance().getBusinessRule(className);
        }
        
        return businessRule;
```
The error in Specify 6 was being caused by `(BusinessRulesIFace)Class.forName(businessRulesClassName)` because there was no Class with name `businessRulesClassName`. 

However, note the branching condition which occurs when `businessRulesClassName` is empty or null. 
For the `class` attribute defined on the view, it fetches the business rules. 

This is resolved primarily through the `BusinessRulesIFace getBusinessRule(Class<?> classOfObj)` methods of `DBTableIdMgr`: 

https://github.com/specify/specify6/blob/945d28f00288d2d64979848fb2fb63fda34bdd1b/src/edu/ku/brc/af/core/db/DBTableIdMgr.java#L720-L742

```java
    public BusinessRulesIFace getBusinessRule(Class<?> classOfObj)
    {
        DBTableInfo ti = getByClassName(classOfObj.getName());
        if (ti != null)
        {
            String br = ti.getBusinessRuleName();
            if (StringUtils.isNotEmpty(br))
            {
                try
                {
                    return (BusinessRulesIFace)Class.forName(br).newInstance();
                    
                } catch (Exception ex)
                {
                    edu.ku.brc.af.core.UsageTracker.incrHandledUsageCount();
                    edu.ku.brc.exceptions.ExceptionTracker.getInstance().capture(DBTableIdMgr.class, ex);
                    log.error("Bad Business Rule class name["+br+"]"); //$NON-NLS-1$ //$NON-NLS-2$
                    log.error(ex);
                }
            }
        }
        return new GenericBusRules();
    }
```
This tries to fetch the default business rules for a given table, or returns a GenericBusiness class if one can not be found. 

The business rules for a table are defined from: https://github.com/specify/specify6/blob/945d28f00288d2d64979848fb2fb63fda34bdd1b/src/edu/ku/brc/af/core/db/DBTableIdMgr.java#L186

```java
                    tblInfo.setBusinessRuleName(XMLHelper.getAttr(tableNode, "businessrule", null)); //$NON-NLS-1$
```
This sets the default business rule for a table to be the class defined in the `businessrule` attribute for the table in the `specify_datamodel.xml` file. 

---

There are some cases that this solution would not cover, however. See https://github.com/specify/specify7/pull/4816#pullrequestreview-2020873267

**Review by alesan99 — APPROVED** [review]

**Review by pashiav — APPROVED** [review]
Looks good! Tested multiple tables that should not have busrules.
Screen Shot 2024-04-24 at 10 51 47 AM

**Review by acwhite211 — APPROVED** [review]

**Review by melton-jason — DISMISSED** [review]
This code will still cause some discrepancies when saving certain default views in Specify 7. 

I wrote a script to extract all cases in the default form definitions for which a view 's  table (extracted from the `class` attribute of the view) does not match the expected `${TABLE_NAME}BusRules` value for the `busrules` attribute on the view.

Here are all above cases that occur in the default view definition files: 

| file                                           | viewName               | class                                       | busRuleClass                                        |
|------------------------------------------------|------------------------|---------------------------------------------|-----------------------------------------------------|
| Specify6.8.03/config/common/common.views.xml  | Shipment               | edu.ku.brc.specify.datamodel.Shipment      | edu.ku.brc.specify.datamodel.busrules.LoanGiftShipmentBusRules             |
| Specify6.8.03/config/backstop/global.views.xml| CatAutoNumberingScheme| edu.ku.brc.specify.datamodel.AutoNumberingScheme | edu.ku.brc.specify.datamodel.busrules.CatAutoNumberingSchemeBusRules |
| Specify6.8.03/config/backstop/global.views.xml| BioStrat               | edu.ku.brc.specify.datamodel.GeologicTimePeriod | edu.ku.brc.specify.datamodel.busrules.BioStratBusRules |
| Specify6.8.03/config/backstop/global.views.xml| TreeDefEditor          | edu.ku.brc.specify.datamodel.TreeDefIface  | edu.ku.brc.specify.datamodel.busrules.TreeDefBusRules |
| Specify6.8.03/config/backstop/global.views.xml| ObjectAttachment       | edu.ku.brc.specify.datamodel.ObjectAttachmentIFace | edu.ku.brc.specify.datamodel.busrules.AttachmentBusRules |
| Specify6.8.03/config/backstop/global.views.xml| ObjectAttachmentIconOnly| edu.ku.brc.specify.datamodel.ObjectAttachmentIFace | edu.ku.brc.specify.datamodel.busrules.AttachmentBusRules |
| Specify6.8.03/config/backstop/global.views.xml| CollectionObjectAttachment| edu.ku.brc.specify.datamodel.CollectionObjectAttachment | edu.ku.brc.specify.datamodel.busrules.AttachmentBusRules |

[results.csv](https://github.com/specify/specify7/files/15099999/results.csv)

We already handle the case for Shipment by using the `LoanGiftShipmentBusRules` whenever the view has the class `edu.ku.brc.specify.datamodel.Shipment`

https://github.com/specify/specify7/blob/4e576e710978a8bd1c96ce2f6091ebe5b236e8ef/specifyweb/frontend/js_src/lib/components/FormEditor/spec.ts#L102-L108

Whenever the other views are saved using the Form Editor in Specify 7, the `busrule` attribute will either not be written to the view (but should exist on the view) or  use an incorrect businessrule class for Specify 6. 

The script used to generate the results is attached:
[parseViews.py.txt](https://github.com/specify/specify7/files/15099981/parseViews.py.txt)

---

While there are only 6 cases left to cover, this issue will occur anytime someone does any of the following:

- Makes and saves a copy of the global.views.xml file-- displayed in the frontend as `Backstop > Global`
- Copies and saves the specific affected view from the file. 
  - For example, copying and saving the BioStrat view when creating a definition for a GeologicTimePeriod (i..e, Chronostratigraphy)

**Comment by melton-jason** [comment]
@specify/ux-testing can this be tested again? 

Testing Instructions have been updated!

**Review by pashiav — APPROVED** [review]
### Testing instructions

- On any ViewSet, add or copy (from the defaults) a new view definition for any of the following tables (non-exhaustive list): AddressOfRecord, ExsiccataItem, MaterialSample, BorrowMaterial
- In the Visual Editor, make any (valid) change on the view definition and save the ViewSet
- [X] In the `XML Editor` view, ensure that the `view` element for the `viewdef` does not contain a `busrule` attribute

---

- On any ViewSet, add or copy (from the defaults) a new view definition for the `Shipment` table
- In the Visual Editor, make any (valid) change on the view definition and save the ViewSet
- [X] In the `XML Editor` view, ensure that the `view` element for the created Shipment view contains `busrule="edu.ku.brc.specify.datamodel.busrules.LoanGiftShipmentBusRules"`

---

- Create a new ViewSet as a copy of `BackStop > Global`
- In the `Visual Editor`, make any change (such as adding/copying a new view definition, modifying an existing view definition) and save the ViewSet
- [X] In the `XML Editor` view, search for `Biostrat` and ensure the Biostrat `view` has `busrule="edu.ku.brc.specify.datamodel.busrules.BioStratBusRules"` 

---

Looks great! Everything works as expected.

**Review by combs-a — COMMENTED** [review]
### Testing instructions

- On any ViewSet, add or copy (from the defaults) a new view definition for any of the following tables (non-exhaustive list): AddressOfRecord, ExsiccataItem, MaterialSample, BorrowMaterial
- In the Visual Editor, make any (valid) change on the view definition and save the ViewSet
- [X] In the `XML Editor` view, ensure that the `view` element for the `viewdef` does not contain a `busrule` attribute

Looking good on both the ones I tested before! Both of them no longer have business rules.

image

image

Additionally tested with Address of Record and Borrow Material, still looked good! Business rules are also still present on Disposal Agent and Loan Items. Not exhaustively tested but it seems to be working well!

---

- On any ViewSet, add or copy (from the defaults) a new view definition for the `Shipment` table
- In the Visual Editor, make any (valid) change on the view definition and save the ViewSet
- [X] In the `XML Editor` view, ensure that the `view` element for the created Shipment view contains `busrule="edu.ku.brc.specify.datamodel.busrules.LoanGiftShipmentBusRules"`

👍 
image

---

- Create a new ViewSet as a copy of `BackStop > Global`
- In the `Visual Editor`, make any change (such as adding/copying a new view definition, modifying an existing view definition) and save the ViewSet
- [ ] In the `XML Editor` view, search for `Biostrat` and ensure the Biostrat `view` has `busrule="edu.ku.brc.specify.datamodel.busrules.BioStratBusRules"` 

This looks good!
image

However, HashTable is (correctly, I believe, since it's a Java class) marked as an unrecognized table. Unsure if this should be staying or not.
image

- [ ] Open any of the modified views in Specify 6 and ensure they are displayed correctly
I can't currently test XML editing between 6 and 7, unfortunately; however, since I got through most of the tests I'm gonna leave this as a comment here for extra reference. 👍

**Review by lexiclevenger — COMMENTED** [review]
- On any ViewSet, add or copy (from the defaults) a new view definition for any of the following tables (non-exhaustive list): AddressOfRecord, ExsiccataItem, MaterialSample, BorrowMaterial
- In the Visual Editor, make any (valid) change on the view definition and save the ViewSet
- [x] In the `XML Editor` view, ensure that the `view` element for the `viewdef` does not contain a `busrule` attribute

---

- On any ViewSet, add or copy (from the defaults) a new view definition for the `Shipment` table
- In the Visual Editor, make any (valid) change on the view definition and save the ViewSet
- [x] In the `XML Editor` view, ensure that the `view` element for the created Shipment view contains `busrule="edu.ku.brc.specify.datamodel.busrules.LoanGiftShipmentBusRules"`

---

- Create a new ViewSet as a copy of `BackStop > Global`
- In the `Visual Editor`, make any change (such as adding/copying a new view definition, modifying an existing view definition) and save the ViewSet
- [x] In the `XML Editor` view, search for `Biostrat` and ensure the Biostrat `view` has `busrule="edu.ku.brc.specify.datamodel.busrules.BioStratBusRules"` 

- [x] Open any of the modified views in Specify 6 and ensure they are displayed correctly
---
Looks good!

**Review by lexiclevenger — APPROVED** [review]

File: specifyweb/frontend/js_src/lib/components/FormEditor/helpers.ts [hunk 5]
```diff
@@ -0,0 +1,104 @@
...
+export const getBusinessRuleClassFromTable = (
+  tableName: keyof Tables
+): string =>
+  businessRulesOverride[tableName] === undefined
+    ? tablesWithBusRulesIn6.has(`${tableName}BusRules`)
+      ? `edu.ku.brc.specify.datamodel.busrules.${tableName}BusRules`
+      : ''
+    : `edu.ku.brc.specify.datamodel.busrules.${businessRulesOverride[
+        tableName
+      ]!}BusRules`;
```
Comment (maxpatiiuk) [inline specifyweb/frontend/js_src/lib/components/FormEditor/helpers.ts:104]: btw, TypeScript 5.5 is much smarter with type inference, so you won't need the `!` in here once we update 🎉

**Review by maxpatiiuk — APPROVED** [review]
8 reviewers assigned on this PR - that might be our record)
