### PR TITLE
Disallow to add rank in create tree dialog

### LINKED ISSUE #5376: Can add TreeDefItems when creating a new tree
**Describe the bug**
When adding a new tree in production (following steps in pr #5080) you can add ranks when treedefitems are rendered as a button and subform but if it is a grid there is no add button. 

**To Reproduce**

1. Go to taxon tree 
2. Click the add button next to tree name 
3. Click any tree 
4. See you can add any rank

**Expected behavior**
Should not be able to add treedefitems

**Screenshots**

https://github.com/user-attachments/assets/90580a56-6cda-4546-8ad1-5f27bab07268

https://github.com/user-attachments/assets/4663a4d1-4746-4e35-8905-32895fc1e16c

Please fill out the following information manually:
- OS: Windows 11
- Browser: Chrome
- Specify 7 Version: production 
- Database Name: nbmmnb20240628
- Collection name: Amphibian and Reptile Observations
- User Name: spadmin
- URL: https://nbmmnb20240628-production.test.specifysystems.org/specify/tree/taxon/?conformation=%7E-

View def: 
```
<viewdef name="TaxonTreeDef" class="edu.ku.brc.specify.datamodel.TaxonTreeDef" type="form" gettable="edu.ku.brc.af.ui.forms.DataGetterForObj" settable="edu.ku.brc.af.ui.forms.DataSetterForObj">
	<desc>The TaxonTreeDef Table</desc>
	<enableRules/>
	<columnDef>p,2px,p,2px,p,2px,p,2px,p,2px,p,p:g</columnDef>
	<rowDef auto="true" cell="p" sep="2px"/>
	<rows>
		<row>
			<cell type="label" labelfor="name"/>
			<cell type="field" id="name" name="name" uitype="text"/>
		</row>
		<row>
			<cell type="label" labelfor="fullNameDir"/>
			<!--   The FullNameDirection picklist can be explicitly specified here, but is inferred because the PickList is assigned at the Schema Config for the field -->
			<cell type="field" id="fullNameDir" name="fullNameDirection" default="1" uitype="combobox"/>
		</row>
		<row>
			<cell type="label" labelfor="remarks"/>
			<cell type="field" id="remarks" name="remarks" uitype="textareabrief" rows="2" colspan="6"/>
		</row>
		<row>
			<!--    Not specifying viewname: Specify is using the view called TaxonTreeDefItem (default for the table)   -->
			<cell type="subview" id="items" name="treeDefItems" colspan="8" defaulttype="form" initialize="sortField=rankId"/>
		</row>
	</rows>
</viewdef>
```

### PR DESCRIPTION
**Pull request by CarolineDenis**
Fixes #5376

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good
      and self-explanatory (or properly documented)
- [ ] Add relevant issue to release milestone

### Testing instructions

Go to taxon tree
Click the add button next to tree name
Click any tree
- [ ] See you cannot add rank using form or table view

### CODE REVIEW

File: specifyweb/frontend/js_src/lib/components/FormSliders/IntegratedRecordSelector.tsx [hunk 1]
```diff
@@ -113,16 +113,16 @@ export function IntegratedRecordSelector({
...
   const isAttachmentTable =
     collection.table.specifyTable.name.includes('Attachment');
 
   const isCOJO =
     relationship.relatedTable.name === 'CollectionObjectGroupJoin' &&
     relationship.name === 'children';
 
+  const isTaxonTreeDefItemTable =
+    collection.table.specifyTable.name === 'TaxonTreeDefItem';
+
```
Comment (sharadsw) [inline specifyweb/frontend/js_src/lib/components/FormSliders/IntegratedRecordSelector.tsx:125]: This will disable adding ranks through the taxontreedefitem subview all across Specify and not just in the tree creation dialog. Is there any place in Specify where we still want the ability to add a rank through the subview?

If so, a potential alternative could be to change the treedef form definition to not show the ranks in the form.

**Review by sharadsw — APPROVED** [review]

**Review by pashiav — APPROVED** [review]
### Testing instructions

Go to taxon tree
Click the add button next to tree name
Click any tree
- [X] See you cannot add rank using form or table view 
---

Looks good! Cannot add tree def items.
Screen Shot 2024-11-06 at 2 05 27 PM
Screen Shot 2024-11-06 at 2 08 02 PM

**Review by acwhite211 — APPROVED** [review]

**Comment by lexiclevenger** [comment]
This also disables the Add button in the Tree Def Items form for existing trees, not just when creating a new Tree Definition. Is this the expected behavior?

https://github.com/user-attachments/assets/123343b1-e6a8-4ab7-aee6-95f825faa7ee

**Comment by CarolineDenis** [comment]
@lexiclevenger, yes
